### ISSUE TITLE
Aggregated endpoint is not visible in SwaggerUI

### ISSUE THREAD

**Issue by AntonukOM** [Burgyn/MMLib.SwaggerForOcelot#106]
Hi, I have a configuration for the aggregated call for my API:
"Aggregates": [
    {
      "RouteKeys": [
        "Tenants",
        "KeycloakUsers"
      ],
      "UpstreamPathTemplate": "/tenantsAndUsers",
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "Bearer",
        "AllowedScopes": []
      }
    }
  ]
But I cannot see this endpoint in my swagger UI.
I use AddSwaggerForOcelot and UseSwaggerForOcelotUI in my Startup.cs file.

**Comment by Burgyn** [comment]
Hi,
unfortunately this project does not support Ocelot Aggregators. Now!
See #24
I plan to do it. But I can't promise a when.

**Comment by AntonukOM** [comment]
Thank you very much for your reply!
I am glad to know that you have plans for that!
BR,
Oleksandr!

чт, 4 черв. 2020 о 15:19 Miňo Martiniak <notifications@github.com> пише:
