### ISSUE TITLE
Deployment to Azure WebAPI Fails due to security filter denying double slash "//"

### ISSUE THREAD

**Issue by yasirk** [Burgyn/MMLib.SwaggerForOcelot#108]
**Describe the bug**
When deploying to Azure Web Api with Ocelot configured as 'self contained' publish profile, MMLib breaks when invoking a call to the swagger.json endpoints. IIS on azure throws a error:

"The request contained a double escape sequence and request filtering is configured on the Web server to deny double escape sequences"

**Expected behavior**
A solution would be to disable request filtering but this exposes several security holes in a production deployment. 

Ideally the config file should not include "http://" prefix and only include the host name. this is possible by using a service discovery gateway, but  I'd hope that a simple update to the code that creates a URI from the config file will fix this. 

**To Reproduce**
Deploy MMLIb with Ocelot to Azure Web API. Configure any swagger config to point to any Azure Web API that exposes swagger.json.

**Comment by yasirk** [comment]
@Burgyn  I'm using ocelot 16.0.1  and below is a sample snippet of the ocelot.json configuration. 

The swagger UI on each individual service loads up fine, however when going through Ocelot is when the load fail/above error shows up. 

{
  "GlobalConfiguration": {
    "BaseUrl": "https://localhost:5001"
    
  },
  "Routes": [
    {
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "https",

      "DownstreamHostAndPorts": [
        {
          "Host": "xxxxxxxxxxxxxxxx.azurewebsites.net",
          "Port": 443
        }
      ],

      "UpstreamPathTemplate": "/dd/{everything}",
      "UpstreamHttpMethod": [ "Get" ],
      "SwaggerKey": "xxxxxxxxxxxxxxxx"
    },
---------------deleted for brevity------------------
   
  "SwaggerEndPoints": [
    {
      "Key": "xxxxxxxxxxxxxxxxx",
      "Config": [
        {
          "Name": "xxxxxxxxxxx API",
          "Version": "v1",
          "Url": "http://XXXXXXXXXXXXXXXX/swagger/v1/swagger.json"
        }
      ]
    },
  ---------------deleted for brevity ----------------


`"openapi": "3.0.1",
"info": {
"title": "Consent Registery",
"version": "v1"
},
"paths": {
"/api/registry/identity/{userEmail}": {
"get": {
"tags": [
"ConsentRegister"
],
"operationId": "GetPartnerIDByUserEmail",
"parameters": [
{
"name": "userEmail",
"in": "path",
"required": true,
"schema": {
"type": "string",
"nullable": true
}
}
],
"responses": {
"200": {
"description": "Success",
"content": {
"application/json": {
"schema": {
"type": "integer",
"format": "int32"
}
}
}
}
}
}
},`

**Comment by Burgyn** [comment]
Hi,
if you have an idea how to implement it out then please make PR.

I currently don't have room to work it out.
thank you and sorry.
