### ISSUE TITLE
no operations defined in spec after upgrading to Version 2.3.0

### ISSUE THREAD

**Issue by luccasmf** [Burgyn/MMLib.SwaggerForOcelot#110]
I'm using the ocelot as a gateway for 4 apis,

Everything was working fine, but, since I updated the SwaggerForOcelot version to 2.3.0, it is being shown that my APIs doesn't have definitions for operation. But, when I rolled back to the version 1.10.5 everything became functional again.

I'm trying to update  Ocelot to 1.6.0.1 and already have changed "ReRoutes" to "Routes" on the ocelot.json file, but then I can't test it since doesn't appear on Swagger

Does someone know how to deal with it ?

**Comment by gromilQaaaa** [comment]
having the same issue, installed fresh latest SwaggerForOcelot - it works when I use .Net Core launcher, but doesn't when I use docker-compose

**Comment by gromilQaaaa** [comment]
Don't forget to set SwaggerKey for each service

**Comment by luccasmf** [comment]
> Don't forget to set SwaggerKey for each service

I change the "SwaggerEndpoints" to SwaggerKey ?

**Comment by luccasmf** [comment]
> Don't forget to set SwaggerKey for each service

![image](https://user-images.githubusercontent.com/5990448/85045018-c6e58d00-b164-11ea-871d-009747e98207.png)

But I'm using it already

**Comment by Burgyn** [comment]
Hi.

version from `2.0.0` references Ocelot `16.0.1` which have breaking change (rename ReRoute to Route).
This package support this changes.

If you have still problem with version 2.5.0, than please provide `ocelot.json` configuration and sample of your downstream `swagger.json`.

Thanks.

**Comment by luccasmf** [comment]
@Burgyn  I'll try the 2.5 version to check, 

With the 2.3 I'd tried the Ocelot 16.0.1, calling the endpoints was working, but The swagger part was not showing information. Thanks for now

**Comment by luccasmf** [comment]
@Burgyn with the 2.5.0 it's working now, thanks for the update, I'll Close the incident

**Comment by Burgyn** [comment]
I'm glad to hear
