### ISSUE TITLE
Configurations override by files with defined environment

### ISSUE THREAD

**Issue by JethroCZ** [Burgyn/MMLib.SwaggerForOcelot#112]
Hello, I have a question.
Is there posibility to set up AddOcelotWithSwaggerSupport to import all files, without defined environment, and override them by configuration from files with defined environment name?
I will have multiple files with Routes, and I want to have defined SwaggerEndPoints by themselves. And for Controllers of gateway itself I will need to define one endpoint for production (using IP address of server) and second for development (using localhost).
I can set it up so it will only take files with current environment in it. But it would mean, that I would have to create duplicate file for each environment and each configuration i want to have, even if there will not be any changes for this file.

file **ocelot.SwaggerEndPoints.json**
```
{
  "SwaggerEndPoints": [
    {
      "Key": "catalog",
      "Config": [
        {
          "Name": "Catalog API",
          "Version": "v1",
          "Url": "http://192.168.6.15:8042/swagger/v1/swagger.json"
        },
        {
          "Name": "Catalog API",
          "Version": "v2",
          "Url": "http://192.168.6.15:8042/swagger/v2/swagger.json"
        }
      ]
    },
    {
      "Key": "gateway",
      "TransformByOcelotConfig": false,
      "Config": [
        {
          "Name": "Gateway API",
          "Version": "v1",
          "Url": "http://192.168.6.15:8002/swagger/v1/swagger.json"
        }
      ]
    }
  ]
}
```

file **ocelot.SwaggeEndPoints.Development.json**
```
{
  "SwaggerEndPoints": [
    {
      "Key": "gateway",
      "TransformByOcelotConfig": false,
      "Config": [
        {
          "Name": "Gateway API",
          "Version": "v1",
          "Url": "http://localhost:8002/swagger/v1/swagger.json"
        }
      ]
    }
  ]
}
```

I want to use configuration from file **ocelot.SwaggerEndPoints.json** everytime. And only when I start app with **environment = Development**, then i want to override only the part where **Key=gateway** from file **ocelot.SwaggerEndPoints.Development.json**.
This way I can use development files only when i really need them (currently it seems that if I want to use environment, it only takes files which have environment name in their name.

**Comment by Burgyn** [comment]
Hi,

unfortunetly current implementation is as you describe. If you have idea how to implement its, you can create PR. Contributions is open :-)

In our projects for different configurations in different environment we use [AppConfiguration Service discovery provider](https://github.com/Burgyn/MMLib.Ocelot.Provider.AppConfiguration). We have one `ocelot.json` file with Route definitions and different `appsettings.json` files where we have service address definitions.

**Comment by JethroCZ** [comment]
Hello, thak you for reply. 

I bet we will soon need some kind of implementation. We might take a look at this service discovery provider you sugested.
Or we might alter swagger for ocelot nuget and send PR:) Only time will tell.

**Comment by AlexanderSysoev** [comment]
@Burgyn could you please show configuration for SwaggerEndPoints section when using suggested library?

**Comment by Burgyn** [comment]
Hi @AlexanderSysoev,

Please take a look at the [ocelot.SwaggerEndpoint](https://github.com/Burgyn/MMLib.SwaggerForOcelot/blob/master/demo/ApiGateway/Configuration/ocelot.SwaggerEndPoints.json) file in this repo.

**Comment by AlexanderSysoev** [comment]
@Burgyn Thank you for your reply! Do the service urls in SwaggerEndPoints section fetch from app configuration or from servers section of swagger.json of downstream service?

**Comment by Burgyn** [comment]
It fetch data from `Configuration` and whether it will be `appsettings.json`, App Configuration or some other sources (e.g. environment variables) depends on how you have configured providers.
