### ISSUE TITLE
The swagger endpoint does not change when hosting the gateway in a virtual directory on IIS

### ISSUE THREAD

**Issue by jigneshnarain** [Burgyn/MMLib.SwaggerForOcelot#113]
When hosting the gateway the in a virtual directory, swagger does not work. Swagger only works when gateway is hosted in the root.

**Expected** /gateway/swagger/docs/v1/servicename
**Actual** /swagger/docs/v1/servicename

When manually navigating /gateway/swagger/docs/v1/servicename, the json is returned as expected.

I've also tried, but no luck.

app.UseSwaggerForOcelotUI(opt => {
	opts.ServerOcelot = "/gateway" ;
})

How do I get swagger to work when hosting the gateway the in a virtual directory?

**Comment by Burgyn** [comment]
Hi,

try to set `VirtualDirectory` property on route definition.

```json
{
  "DownstreamPathTemplate": "/project/api/{everything}",
  "DownstreamScheme": "http",
  "DownstreamHostAndPorts": [
      {
      "Host": "localhost",
      "Port": 5100
      }
  ],
  "UpstreamPathTemplate": "/api/project/{everything}",
  "UpstreamHttpMethod": [ "Get" ],
  "SwaggerKey": "project",
  "VirtualDirectory":"/project"
}
```

[see readme - virtual directory](https://github.com/Burgyn/MMLib.SwaggerForOcelot#virtual-directory)

**Comment by jigneshnarain** [comment]
This does not work as my downstream services are self-hosted and only the gateway is hosted in a virtual directory. A solution would be to change the relative path of the swagger ui endpoint to "**../**swagger/v1/swagger.json" (https://bartwullems.blogspot.com/2018/08/aspnet-coreswagger-error-when-using.html). I have test this but the relative path does not work.

**Comment by Burgyn** [comment]
Hi,

try to set property `PathToSwaggerGenerator`.

```CSharp
app.UseSwaggerForOcelotUI(opt => {
  opt.PathToSwaggerGenerator = "/gateway/swagger/docs";
})
```

I didn't test it, currently I don't have time to simulate this. Sorry.

**Comment by jigneshnarain** [comment]
Hi

I resolved the issue. I needed to set the DownstreamSwaggerEndPointBasePath

app.UseSwaggerForOcelotUI(opt => {
  opt.DownstreamSwaggerEndPointBasePath = "../swagger/docs";
})
