### ISSUE TITLE
Customize Swagger UI

### ISSUE THREAD

**Issue by abodehq** [Burgyn/MMLib.SwaggerForOcelot#118]
Great Library Thanks,

I just want to know how we can customize the swagger ui ( inject custom css and index.html)

it will be great if you can show us some simple example//

thanks again.

**Comment by Burgyn** [comment]
Hi @abodehq,

I've never tested its. But you can try this tutorial for [Swashbuckle](https://code-maze.com/swagger-ui-asp-net-core-web-api/). Section **Customizing the UI**.
