### ISSUE TITLE
Api gateway swagger not read microservice swagger json 

### ISSUE THREAD

**Issue by tayfunuyar** [Burgyn/MMLib.SwaggerForOcelot#119]
Hi guys,
I have a problem with read microservice swagger.json.
Can you help me please?
![image](https://user-images.githubusercontent.com/27923376/89767767-40fe1680-db03-11ea-8137-cf84157b51eb.png)

**Comment by Burgyn** [comment]
Hi,

Please can you provide downstream `swagger.json` and your `ocelot.json` files?

thnaks.

**Comment by tayfunuyar** [comment]
I change https configuration.Now working.Thank you for response.
