### ISSUE TITLE
With version 1.9.0 the http scheme is duplicated

### ISSUE THREAD

**Issue by fr4nky80** [Burgyn/MMLib.SwaggerForOcelot#121]
**Describe the bug**
Only happens with swagger version 2
SwaggerForOcelotMiddleware method invoke, you use this:
```  c#
  var hostName = endPoint.EndPoint.HostOverride ?? UriHelper.BuildAbsolute(context.Request.Scheme, context.Request.Host).RemoveSlashFromEnd();
```
but in version 1.4.0 use this:
``` c#
 var hostName = endPoint.EndPoint.HostOverride ?? context.Request.Host.Value;
```` 

this makes the HTTP requests duplicate the scheme, example:

http://http://localhost

**Expected behavior**
should be localhost but it's http://localhost, which means that the api calls are incorrect since it includes twice the scheme.

**To Reproduce**
just include version 1.9.0 and expose a service from the gw.

**Comment by Burgyn** [comment]
Hi,
thanks for your issue.

This issue looks the same as #117.

I'll try to fix it next week.
As a tempolary workaround, you can try to setting the `HostOverride` property to `""`.

```json
  "SwaggerEndPoints": [
    {
      "Key": "user",
      "HostOverride": "",
      "Config": [
        {
          "Name": "User API",
          "Version": "v1",
          "Url": "http://localhost:7071/api/swagger.json"
        }
      ]
    }
  ],
```

**Comment by fr4nky80** [comment]
Thanks this works!!!
