### ISSUE TITLE
Undefined 

### ISSUE THREAD

**Issue by FiskaniC** [Burgyn/MMLib.SwaggerForOcelot#124]
**Describe the bug**
Fetch error: undefined /gateway/swagger/docs/v1/contacts. When trying to run the demo application I get this error. Also when trying to run the package in my Ocelot apigatway.

**Expected behavior**
Should be able to navigate through the different apis

**To Reproduce**
Get demo solution. Run services and apigateway.

![image](https://user-images.githubusercontent.com/40929607/94157931-0e756680-fe82-11ea-9fe4-3689e5239f47.png)

**Comment by Burgyn** [comment]
Hi,
please can you check the address where your instance of `companies` service is running?
In configuration is set `http://localhost:5100`. Is your instance of `companies` running on this address?

**Comment by FiskaniC** [comment]
It worked thanks. I was configuring swagger on the Ocelot api itself which broke. Removing the swagger confit worked.

Warm Regards

Fiskani Chirwa
Cell: 0718707091
