### ISSUE TITLE
MMLib - 404 error occurs when running Swagger

### ISSUE THREAD

**Issue by djesusnet** [Burgyn/MMLib.SwaggerForOcelot#129]
**Describe the bug**
I'm using the latest version, but I can't run the swagger, because a 404 error occurs.

**Expected behavior**
Expected behavior was to run the swaggers that are configured in appsettings.

**To Reproduce**
If it is a possible attache:
1. Original downstream `swagger.json`.
2. Ocelot ReRoutes configuration.
[appsettings.Development.zip](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/5384209/appsettings.Development.zip)

repository git:
https://github.com/djesusnet/ExampleConfigSwaggerExampleApiGatewayOcelot

**Comment by Burgyn** [comment]
Hi @djesusnet 

You use Ocelot with version `16.0.1.` [which have breaking change](https://github.com/ThreeMammals/Ocelot/releases/tag/16.0.0), that rename `ReRoutes` -> `Routes` and you still using `ReRoutes` in your configuration.

Try rename `ReRoutes` to `Routes` and remove property `TransformByOcelotConfig` from `SwaggerEndPoints`.

**Comment by djesusnet** [comment]
Hi @Burgyn,

Thank you so much, it worked!

**Comment by Burgyn** [comment]
I like hear that.
