### ISSUE TITLE
Add support for DelegatingHandlers to outgoing HTTP calls

### ISSUE THREAD

**Issue by hallidev** [Burgyn/MMLib.SwaggerForOcelot#130]
**Is your feature request related to a problem? Please describe.**
We need to pass certificates from our Ocelot gateway to underlying APIs. To handle this requirement, we need to add a DelegatingHandler to the call from the gateway to underlying API.

**Describe the solution you'd like**
Ocelot supports the following:

```
            services
                .AddOcelot()
                .AddDelegatingHandler<CertificateHandler>(true);
```

Could Swagger for Ocelot support something similar?

**Additional context**
Do you accept PRs? We could put together a PR for this.

**Comment by Burgyn** [comment]
Hi,
Unfortunately, this package does not currently support this.
PRs are open. So if you have an idea how to implement it, I will be grateful for your help

**Comment by hallidev** [comment]
A colleague is putting together a PR now
