### ISSUE TITLE
I would like to be able to control who can access certain endpoints, also control the visibility/availability of the endpoints.

### ISSUE THREAD

**Issue by Hantsch** [Burgyn/MMLib.SwaggerForOcelot#136]
Hello,

I have the scenario to control access to certain endpoints (either under development, or for internal use only).
To be able to see swagger endpoints on the API Gateway you need to be logged in. I use the roles of the user to determine if he can view certain endpoints like (api_view_oders_v2). With this solution I can only restrict the view not the access so I would need a middleware or interceptor which I can inject to check wehter the user is allowed to access the endpoint or not.

I am currently using a local cloned version of this repository to do so, but it would be nice to include a feature like that.
Therefor I created a fork with a feature branch: https://github.com/Hantsch/MMLib.SwaggerForOcelot/tree/feature/swagger-downstream-interceptor

The main idea is an injectable interface via DI to control the downstream. When injected you are free to control how you want to check wehter the downstream should be done or not.

I also created an example API gateway to showcase the implementation.

This is also related to my earlier request (sorry I could not follow up): #120

**Comment by Burgyn** [comment]
Hi,

thanks for discribing this issue and your effort. Your implementation looks good. Please can you provide Pull Request from your fork?
If yes, please add few words about it to documentation in readme file.

Thanks.

**Comment by Hantsch** [comment]
Sure will do that, thanks.

**Comment by Burgyn** [comment]
Yes, directly in `readme.md` file. 

Thanks.

**Comment by Burgyn** [comment]
Thanks for help. This feature will be release as version `v_3.0.1` in a few minutes.
