### ISSUE TITLE
DownstreamScheme is lost 

### ISSUE THREAD

**Issue by mcslove808** [Burgyn/MMLib.SwaggerForOcelot#142]
**Describe the bug**
System.UriFormatException: Invalid URI: The URI scheme is not valid.

 private string GetScheme(ServiceHostAndPort service, RouteOptions route)
            => (route != null && !route.DownstreamScheme.IsNullOrEmpty())
            ? route.DownstreamScheme
            : !service.Scheme.IsNullOrEmpty()
            ? service.Scheme
            : service.DownstreamPort
            switch
            {
                443 => Uri.UriSchemeHttps,
                80 => Uri.UriSchemeHttp,
                _ => string.Empty,
            };
result is empty because DownstreamScheme is lost
 public static IEnumerable<RouteOptions> GroupByPaths(this IEnumerable<RouteOptions> routeOptions)
            => routeOptions
            .GroupBy(p => new { p.SwaggerKey, p.UpstreamPathTemplate, p.DownstreamPathTemplate, p.VirtualDirectory})
            .Select(p => {
                RouteOptions route = p.First();
                return new RouteOptions(
                    p.Key.SwaggerKey,
                    route.UpstreamPathTemplate,
                    route.DownstreamPathTemplate,
                    p.Key.VirtualDirectory,
                    p.Where(r => r.UpstreamHttpMethod != null).SelectMany(r => r.UpstreamHttpMethod))
                {
                    DownstreamHttpVersion = route.DownstreamHttpVersion,
                    //DownstreamScheme = route.DownstreamScheme

                };
            });

**Expected behavior**

**To Reproduce**
If it is a possible attache:
1. Original downstream `swagger.json`.
2. Ocelot ReRoutes configuration.

**Comment by Burgyn** [comment]
Hi,

thank you for your issue. Unfortunately, from this description I do not understand what is wrong. Please try to describe it more clearly. Well thank you.

**Comment by mcslove808** [comment]
Hi,
I see you've just added it
DownstreamScheme = route.DownstreamScheme
You can update The SwaggerForOcelot version of NetCoRE3.1 on Nuget.org, which I'm using

**Comment by Burgyn** [comment]
Hi,

for you 😉 I fixed it to version `3.1.1`. Try it.

https://www.nuget.org/packages/MMLib.SwaggerForOcelot/3.1.1

**Comment by mcslove808** [comment]
thank you
