### ISSUE TITLE
IndexOutOfRangeException when accessing swagger/docs

### ISSUE THREAD

**Issue by boonto** [Burgyn/MMLib.SwaggerForOcelot#146]
**Describe the bug**
I get a
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at MMLib.SwaggerForOcelot.Middleware.SwaggerForOcelotMiddleware.GetEndPointInfo(String path)
```
when running the demo `APIGateway` and accessing `/swagger/docs`. it does not matter whether one or more services are running in the background. It seems this is caused due to an empty `context.Request.Path` in `SwaggerForOcelotMiddleware.Invoke()`.

**Expected behavior**
No exception.

**To Reproduce**
If it is a possible attache:
1. `dotnet run` in `demo/ApiGateway`
2. Access `localhost:5000/swagger/docs`

**Comment by n-shay** [comment]
`/swagger/docs` is expecting the service/endpoint version and key in the following format: `/swagger/docs/v1/orders`.

The key and version are the values from "SwaggerEndPoints" settings.

**Comment by Burgyn** [comment]
Hi,

as @n-shay  says, when you want got docs json, you have to add version and endpoint to path. When you want show documentation, access `http://localhost:5000/swagger/index.html`.

**Comment by boonto** [comment]
Oh sure, the individual endpoints work fine. I just wasn't expecting to get the exception, rather a 404 or something similar.

**Comment by Burgyn** [comment]
Hi @boonto,

I'm glad to hear it works. Yes `404` would be better.
