### ISSUE TITLE
Failed to load API definition.

### ISSUE THREAD

**Issue by RonniePoulsen** [Burgyn/MMLib.SwaggerForOcelot#147]
Hi,

I am not quite sure whether this issue has to do with Ocelot or Swagger configuration. But here goes.

On our project we have an Ocelot application (aspnet core 3.1) which, so far, has one downstream microservice and additional microservices coming over time. Now I am in the process of setting up SwaggerForOcelot, but something is killing me in the configuration part. 

**Describe the bug**
Our Ocelot application is running at localhost:44382/gateway/ and the microservice is running in the background. Swagger is not present at this root url. When trying to access localhost:44382/gateway/index.html I'm getting the error "Failed to load API definition". At localhost:44382/gateway/swagger/v1/swagger.json I can reach the Swagger file of our microservice. But it seems that Swagger cannot find the file. Requests to the microservice through Ocelot are working perfect, so this must be a Swagger issue. Swagger is set up on the microservice and is working perfect too.

When removing "gateway/" part from the url in ocelot.json and launchSettings.json, Swagger is suddenly present at the root url localhost:44382/index.html. What am I missing here? Am I supposed to register the "gateway/" part somewhere else to get this working?

**Expected behavior**
I would expect Swagger to appear at localhost:44382/gateway/index.html.

**To Reproduce**
ocelot.json
```
{
  "Routes": [
    {
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44310
        }
      ],
      "UpstreamPathTemplate": "/gateway/{everything}",
      "UpstreamHttpMethod": [ "GET" ],
      "DangerousAcceptAnyServerCertificateValidator": false,
      "RouteIsCaseSensitive": false,
      "UpstreamHeaderTransform": {
        "Secret": "************"
      },
      "SwaggerKey": "klientaktiviteter"
    }
  ],
  "SwaggerEndPoints": [
    {
      "Key": "klientaktiviteter",
      "Config": [
        {
          "Name": "Klient Aktiviteter v1",
          "Version": "v1",
          "Url": "https://localhost:44310/swagger/v1/swagger.json"
        }
      ]
    }
  ] 
}
```
Startup.cs ConfigureServices()
```
services.AddSwaggerForOcelot(Configuration);
```
Startup.cs Configure()
```
app.UseSwaggerForOcelotUI(opts =>
            {
                opts.PathToSwaggerGenerator = "/swagger/docs";
                opts.RoutePrefix = string.Empty;
            });
```
launchSettings.json
```
"profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "gateway/",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
}
```

Thank you.

**Comment by RonniePoulsen** [comment]
Hi,
Just a note. Same thing happens for me when running your demo application. So it seems that the issue is not specific for my application?

**Comment by Burgyn** [comment]
Hi @RonniePoulsen 
thanks for your issue.

Please try the following configuration:
```CSharp
app.UseSwaggerForOcelotUI(opts =>
{
  opts.RoutePrefix = "gateway";
});
```

And try launch swagger docs UI at ` localhost:44382/gateway`.

**Comment by RonniePoulsen** [comment]
Hi @Burgyn,
I have tried what you proposed.
```
app.UseSwaggerForOcelotUI(opts =>
{
  opts.RoutePrefix = "gateway";
});
```
But it doesn't change anything. I'm still getting the same error message **"Failed to load API definition"**.

I noticed these two errors in the output window of Visual Studio on startup, but can't figure out what it means:

`Ocelot.Responder.Middleware.ResponderMiddleware: Warning: requestId: 800001d2-0001-ff00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Error Code: UnableToFindDownstreamRouteError Message: Failed to match Route configuration for upstream path: /gateway/, verb: GET. errors found in ResponderMiddleware. Setting error response for request path:/gateway/, request method: GET`

`Ocelot.Responder.Middleware.ResponderMiddleware: Warning: requestId: 800001d8-0001-ff00-b63f-84710c7967bb, previousRequestId: no previous request id, message: Error Code: UnableToFindDownstreamRouteError Message: Failed to match Route configuration for upstream path: /swagger/v1/swagger.json, verb: GET. errors found in ResponderMiddleware. Setting error response for request path:/swagger/v1/swagger.json, request method: GET`

I really can't figure out, if this is a Ocelot configuration or if it is related to Swagger or SwaggerForOcelot. The funny thing is that, when I look at your demo by running the ContactService, OrderService and the ApiGateway, I'm getting the same error. It seems that Swagger doesn't find the definition files at all.

Again. Am I missing something completely basic in this?

Btw. Thank you very much for pointing out the problem with my secret.

**Comment by Burgyn** [comment]
Hi,
I am not currently at the PC. At first glance it looks (from mobile) that Ocelot is trying to find a route configuration for request from SwaggerUI. Is's because `/gateway/{everything}`. For testing, try next configuration:
```csharp
app.UseSwaggerForOcelotUI(opts =>
{
  opts.RoutePrefix = "swagger";
});
```

And try launch swagger docs UI at `localhost:44382/swagger`.

If that doesn't help, I'll look into it tomorrow

**Comment by RonniePoulsen** [comment]
Hi @Burgyn,
That doesn't work either.

To understand how your library works, I have been looking at your demo. But as I mentioned in my previous comment, that doesn't work for me either. When running the ContactService, OrderService and the ApiGateway together, I would expect to be able to view Swagger schemes for these services. I can choose the services and versions from the drop down menu. But the same "Failed to load API definition" error appears for all of them even though they're running. Are you sure that a general bug could not be the reason for this?

I hope we can fix this somehow soon.

Thanks again :)

**Comment by Burgyn** [comment]
Hi @RonniePoulsen,

I can't rule out a general bug, but I don't suppose. Because this package is used by many users and no such issues have been reported.

---

- What version of this package are you using? Respectively, in the case of a demo, which version do you have downloaded?
- On which ports are the services running? Gateway expect `ContactService`:`5100` and `OrderService`:`5400`.
- [Please try this demo.](https://github.com/Burgyn/Sample.ApiGatewayOcelot) Pay attention to the ports on which the downstream services will be running.

Thanks.
