### ISSUE TITLE
Path parameter custom type disappears during transformation

### ISSUE THREAD

**Issue by simbadltd** [Burgyn/MMLib.SwaggerForOcelot#149]
**Describe the bug**
Some references could not be resolved through ocelot while they're exist in the original swagger json.

In the following sample `GET /api/test` has parameter with type `ProblemRequestFilter` and response with type `RecordsModel`.  But transformed json doesn't contain `ProblemRequestFilter`.

**Expected behavior**
`ProblemRequestFilter` type exists in processed swagger json

**To Reproduce**
[original_swagger.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/5902982/original_swagger.txt)
[transformed_swagger.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/5902981/transformed_swagger.txt)
[ocelot.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/5902983/ocelot.txt)

Thanks.

**Comment by Burgyn** [comment]
Hi,

thanks for reporting this issue.
It's fixed by PR #150 and will be release in a few minutes as version `4.0.1`.
