### ISSUE TITLE
Swagger Endpoint not working with ingress

### ISSUE THREAD

**Issue by Kum4r4n** [Burgyn/MMLib.SwaggerForOcelot#165]
HI,
Now I am deploying the microservices in azure Kubernetes, for the time I am using an ingress controller with the path after path is defined, 
swagger not working for all services 

![image](https://user-images.githubusercontent.com/31638942/108929832-c04fd380-766a-11eb-972e-9ae4d4675dc6.png)

this is ingress path define

`apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bubl-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite /cu-gw/(.*) /$1 break;
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: customer-gw
          servicePort: 80
        path: /cu-gw(.*)`

without path setting, swagger is worked, how can I fix that?

**Comment by Burgyn** [comment]
Hi @Kum4r4n, 
Can you please provide more detailed information? 
I have no experience with Ingress. So I have no idea what's going on there.

Thanks.
