### ISSUE TITLE
Swagger is not working  in v4.4.1 but is working 4.4.0

### ISSUE THREAD

**Issue by can-acar** [Burgyn/MMLib.SwaggerForOcelot#172]
**Describe the bug**
Hey mate i want to  report  an error:
- SwaggerForOcelot 4.4.1 with Swagger not working on .Net Core 5.0.202 but request pipeline is working 
- SwaggerForOcelot 4.4.0 with Swagger is working on .Net Core 5.0.202 but request pipeline isn't working

**Comment by Burgyn** [comment]
Hi @can-acar,

Please can you specify in more detail what exactly does not work? 
Can you prepare a demo where you reproduce the problem? 

Thank you.
