### ISSUE TITLE
Error While generating Documentation for the Aggregates

### ISSUE THREAD

**Issue by ashwindersingh** [Burgyn/MMLib.SwaggerForOcelot#175]
I have multiple aggregates routes in the ocelot. The routes work perfectly fine if we make a request, but when i try to use swagger for aggregates it throws error saying same key is already added. Isn't Swagger should able to generate documentation for ocelot aggregates if routes works.

```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentException: An item with the same key has already been added. Key: Custom
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
         at MMLib.SwaggerForOcelot.Aggregates.AggregateRouteDocumentationGenerator.CreateResponseSchema(IEnumerable`1 routes, SwaggerAggregateRoute aggregateRoute, OpenApiDocument openApiDocument)
         at MMLib.SwaggerForOcelot.Aggregates.AggregateRouteDocumentationGenerator.GenerateDocs(SwaggerAggregateRoute aggregateRoute, IEnumerable`1 routes, OpenApiDocument openApiDocument)
         at MMLib.SwaggerForOcelot.Aggregates.AggregateRouteDocumentationGenerator.GenerateDocs(SwaggerAggregateRoute aggregateRoute, OpenApiDocument openApiDocument)
         at MMLib.SwaggerForOcelot.Aggregates.AggregatesDocumentFilter.Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
         at MMLib.SwaggerForOcelot.Middleware.SwaggerForOcelotMiddleware.Invoke(HttpContext context, ISwaggerEndPointProvider swaggerEndPointRepository, IDownstreamSwaggerDocsRepository downstreamSwaggerDocs)
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
```
{
  "Routes": [
    {
      "UpstreamPathTemplate": "/OrderManagement/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
      "DownstreamPathTemplate": "/OrderManagement/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44352
        }
      ],
      "SwaggerKey": "order",
      "QosOptions": {
        "TimeoutValue": 300000
      }
    },
    {
      "UpstreamPathTemplate": "/LeadManagement/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
      "DownstreamPathTemplate": "/LeadManagement/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44314
        }
      ],
      "SwaggerKey": "lead",
      "QosOptions": {
        "TimeoutValue": 300000
      }
    },
    {
      "UpstreamPathTemplate": "/ApplicationManagement/health",
      "UpstreamHttpMethod": [ "Get" ],
      "DownstreamPathTemplate": "/health",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44384
        }
      ]
    },
    {
      "UpstreamPathTemplate": "/ApplicationManagement/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
      "DownstreamPathTemplate": "/ApplicationManagement/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44384
        }
      ],
      "SwaggerKey": "application",
      "QosOptions": {
        "TimeoutValue": 300000
      }
    },
    //when Client multiple services results are independent.

    {
      "Key": "OrderService",
      "UpstreamPathTemplate": "/OrderManagement/Cart/GetCart",
      "UpstreamHttpMethod": [ "Get" ],
      "DownstreamPathTemplate": "/OrderManagement/Cart/GetCart",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44352
        }
      ],
      "SwaggerKey": "order"
    },
    {
      "Key": "LeadService",
      "UpstreamPathTemplate": "/LeadManagement/Lead/get",
      "UpstreamHttpMethod": [ "Get" ],
      "DownstreamPathTemplate": "/LeadManagement/Lead/get",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44314
        }
      ],
      "SwaggerKey": "lead"
    },

    {
      "Key": "orderhealth",
      "UpstreamPathTemplate": "/OrderManagement/health",
      "DownstreamPathTemplate": "/health",
      "UpstreamHttpMethod": [ "Get" ],
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44352
        }
      ]
    },
    {
      "Key": "leadhealth",
      "UpstreamPathTemplate": "/LeadManagement/health",
      "DownstreamPathTemplate": "/health",
      "UpstreamHttpMethod": [ "Get" ],
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44314
        }
      ]
    }
  ],
  "Aggregates": [
    {
      "RouteKeys": [
        "OrderService",
        "LeadService"
      ],
      "Description": "Custom description for this aggregate route.",
      "UpstreamPathTemplate": "/api/ils/combine",
      "Aggregator": "CustomAggregator"
    },
    {
      "RouteKeys": [ "orderhealth", "leadhealth" ],
      "Description": "Health for the services",
      "UpstreamPathTemplate": "/api/health",
      "Aggregator": "HealthAggregator"
    }
  ],
  "SwaggerEndPoints": [
    {
      "Key": "order",
      "TakeServersFromDownstreamService": true,
      "Config": [
        {
          "Name": "Order Management API",
          "Version": "v1",
          "Url": "https://localhost:44352/swagger/v1/swagger.json"
        }
      ]
    },
    {
      "Key": "lead",
      "TakeServersFromDownstreamService": true,
      "Config": [
        {
          "Name": "Lead Management API",
          "Version": "v1",
          "Url": "https://localhost:44314/swagger/v1/swagger.json"
        }
      ]
    },
    {
      "Key": "application",
      "TakeServersFromDownstreamService": true,
      "Config": [
        {
          "Name": "Application Management API",
          "Version": "v1",
          "Url": "https://localhost:44384/swagger/v1/swagger.json"
        }
      ]
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "https://localhost:5021"
  }
}
```

**Comment by Burgyn** [comment]
Hi,

thanks for your report. Please can you provide swagger docs of your downstream services? (`OrderService`, `LeadService`)

Thanks.

**Comment by ashwindersingh** [comment]
Health endpoint are the .Net Core Middleware health point

**Order Service** 

// 20210517092624
// https://localhost:44352/swagger/v1/swagger.json

{
  "openapi": "3.0.1",
  "info": {
    "title": "ILS OrderManagement API",
    "description": "OrderManagement API for ILS",
    "version": "v1"
  },
  "paths": {
    "/OrderManagement/Cart/GetCart": {
      "get": {
        "tags": [
          "Cart"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/Cart"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Cart"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Cart"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "oauth2": [
              "LeadsAPI_Full"
            ]
          }
        ]
      }
    },
    "/OrderManagement/Cart/AddToCart": {
      "post": {
        "tags": [
          "Cart"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Cart"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Cart"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Cart"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/Cart"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Cart"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Cart"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        },
        "security": [
          {
            "oauth2": [
              "LeadsAPI_Full"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "Cart": {
        "type": "object",
        "properties": {
          "cartId": {
            "type": "integer",
            "format": "int32"
          },
          "cartName": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "ProblemDetails": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "detail": {
            "type": "string",
            "nullable": true
          },
          "instance": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": {
          
        }
      }
    },
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://localhost:5001/connect/authorize",
            "tokenUrl": "https://localhost:5001/connect/token",
            "scopes": {
              "LeadsAPI_Full": "Integrity Lead Store Application"
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "oauth2": [
        
      ]
    }
  ]
}

**Lead Service**

// 20210517092718
// https://localhost:44314/swagger/v1/swagger.json

{
  "openapi": "3.0.1",
  "info": {
    "title": "ILS LeadManagement API",
    "description": "LeadManagement API for the ILS",
    "version": "v1"
  },
  "paths": {
    "/LeadManagement/Lead/get": {
      "get": {
        "tags": [
          "Lead"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/WeatherForecast"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WeatherForecast"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/WeatherForecast"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "oauth2": [
              "LeadsAPI_Full"
            ]
          }
        ]
      }
    },
    "/LeadManagement/Lead/post": {
      "post": {
        "tags": [
          "Lead"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/WeatherForecast"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/WeatherForecast"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/WeatherForecast"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/WeatherForecast"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/WeatherForecast"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/WeatherForecast"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "oauth2": [
              "LeadsAPI_Full"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "WeatherForecast": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "temperatureC": {
            "type": "integer",
            "format": "int32"
          },
          "temperatureF": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
          "summary": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    },
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://localhost:5001/connect/authorize",
            "tokenUrl": "https://localhost:5001/connect/token",
            "scopes": {
              "LeadsAPI_Full": "Integrity Lead Store Application"
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "oauth2": [
        
      ]
    }
  ]
}

**Comment by Burgyn** [comment]
Hi,

unfortunately I can't reproduce it.
With the information you provided, the documentation will display correctly, see below.
Can you provide an runable sample project that reproduces this behavior?
Many thanks.

![image](https://user-images.githubusercontent.com/5930822/118712269-e2e42980-b820-11eb-8098-892865d27bb1.png)

**Comment by ashwindersingh** [comment]
Can you please add another aggregate route?. It works for me also until I create the second aggregate route.

**Comment by Burgyn** [comment]
I don't quite understand what you mean. 
Because I have added two aggregate routes, just like you:

```json
"Aggregates": [
  {
    "RouteKeys": [
      "OrderService",
      "LeadService"
    ],
    "Description": "Custom description for this aggregate route.",
    "UpstreamPathTemplate": "/api/ils/combine"
  },
  {
    "RouteKeys": [ "orderhealth", "leadhealth" ],
    "Description": "Health for the services",
    "UpstreamPathTemplate": "/api/health"
  }
],
```

With two exceptions:
1. I don't use custom aggregators (I don't have your implementation and I don't think it affects it. Maybe yes.)
2. I have fill property `SwaggerKey` in `leadhealth` and `orderhealth`. Without that it fails on a completely different exception.

```json
{
  "Key": "orderhealth",
  "UpstreamPathTemplate": "/OrderManagement/health",
  "DownstreamPathTemplate": "/health",
  "UpstreamHttpMethod": [ "Get" ],
  "DownstreamScheme": "http",
  "DownstreamHostAndPorts": [
    {
      "Host": "localhost",
      "Port": 5400
    }
  ],
  "SwaggerKey": "order"
},
{
  "Key": "leadhealth",
  "UpstreamPathTemplate": "/LeadManagement/health",
  "DownstreamPathTemplate": "/health",
  "UpstreamHttpMethod": [ "Get" ],
  "DownstreamScheme": "http",
  "DownstreamHostAndPorts": [
    {
      "Host": "localhost",
      "Port": 5300
    }
  ],
  "SwaggerKey": "lead"
}
```
