### ISSUE TITLE
Route with catch all parameters are not shown

### ISSUE THREAD

**Issue by ilcos91** [Burgyn/MMLib.SwaggerForOcelot#176]
In my microservices I have some route with catch all parameters ({**param}), like this:
![image](https://user-images.githubusercontent.com/59659091/118271784-07a76c80-b4c2-11eb-9d30-16efc48315e4.png)
If I go to the microservice swagger I can see them:
![image](https://user-images.githubusercontent.com/59659091/118272138-75ec2f00-b4c2-11eb-91f7-c9a00fa6a672.png)
But on the ocelot swagger they are not shown.
This is not a problem on the Ocelot side since it forwards the requests correctly, the only thing missing is the documentation on the ocelot swagger.

Am I doing something wrong? Do you have any suggestion?

**Comment by Burgyn** [comment]
Hi.

Sorry, but this is [known actual limitation](https://github.com/Burgyn/MMLib.SwaggerForOcelot#limitation).

[There is an issue for that.](https://github.com/Burgyn/MMLib.SwaggerForOcelot/issues/68)
I plan to work it out, but I don't have time for it at the moment.
If you want, PR are open :-)
