### ISSUE TITLE
Totally lost with "No operations defined in spec!" message

### ISSUE THREAD

**Issue by cctron** [Burgyn/MMLib.SwaggerForOcelot#178]
Hi there, I've recently discovered this library for Ocelot projects.

I was trying to implement it in my solution step-by-step, but I can't see the paths in the swagger

![image](https://user-images.githubusercontent.com/35351762/122070060-f2419d00-cdf5-11eb-9ee7-383eba7bc403.png)

I was looking for this issue in other post and testing any differents solutions but it don't still work.

Could you help me?

My solution is in .NEt 5.0, MMLib.SwaggerForOcelot is 4.4.1 version and Ocelot is 17.0.0

The content of the json is (as you can imagine):
`{
  "openapi": "3.0.1",
  "info": {
    "title": "RetrieveExpedientsGateway",
    "version": "v1"
  },
  "paths": {},
  "components": {
    "schemas": {}
  }
}`

in https://localhost:5001/swagger/docs/v1/retrieve

I'll attach you the comple swagger.json
[swagger.json.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/6656367/swagger.json.txt)

I'm not using ocelot.json because we have different environments and we handle it through configuration.ENVIRONMENT.json,
Here is it:
[configuration.development.json.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/6656380/configuration.development.json.txt)

And my Startup.cs:
`public void ConfigureServices(IServiceCollection services)
        {
            services.AddOcelot();
            services.AddSwaggerForOcelot(Configuration);
            services.AddMvc();

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "RetrieveExpedientsGateway", Version = "v1" });
            });

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();
            app.UseSwagger();
            
            app.UseStaticFiles();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Hello World!");
                });
            });

            app.UseSwaggerForOcelotUI();
            
            
            app.UseOcelot().Wait();
            
            
        }`

Thanks in advance.

**Comment by Burgyn** [comment]
Hi,
thanks for your issue.

Are you sure you have attached a complete `swagger.json` file? Because I only see two paths in it, `/configuration` and `/outputcache/{region}`. And in Ocelot definitions, I don't see a routing rule for these routes.

Thanks.

**Comment by cctron** [comment]
> Hi,
> thanks for your issue.
> 
> Are you sure you have attached a complete `swagger.json` file? Because I only see two paths in it, `/configuration` and `/outputcache/{region}`. And in Ocelot definitions, I don't see a routing rule for these routes.
> 
> Thanks.

Good morning Burgyn.

Yes, this is the complete swagger.json generated by the application. There isn't any controllers in the project, I only use the ocelot gateway as a bridge between the client and our APIs (We wan't that the client knows the real endpoint of the other services) . It can be the problem? 

I'm going to add a dummy controller with the same route as appear in Upstream to test if in the swagger.json the path is generated.

I'll post the results later.

Thanks. ^_^

**Comment by Burgyn** [comment]
Hi.
One of the main features is the transformation of downstream documentation into upstream. Translation of paths, removal of paths that are not routed outside through ocelot, removal of unused components.

If you just want to publish the downstream documentation, you can set parameter `TransformByOcelotConfig` to `false`

```json
  "SwaggerEndPoints": [
    {
      "Key": "retrieve",
      "TransformByOcelotConfig": false,
      "Config": [
        {
          "Name": "RetrieveExpedientsGateway API",
          "Version": "v1",
          "Url": "https://localhost:5001/swagger/v1/swagger.json"
        }
      ]
    }
  ]
```

I hope this helps you.

I wish you have a nice day.

**Comment by cctron** [comment]
> > Hi,
> > thanks for your issue.
> > Are you sure you have attached a complete `swagger.json` file? Because I only see two paths in it, `/configuration` and `/outputcache/{region}`. And in Ocelot definitions, I don't see a routing rule for these routes.
> > Thanks.
> 
> Good morning Burgyn.
> 
> Yes, this is the complete swagger.json generated by the application. There isn't any controllers in the project, I only use the ocelot gateway as a bridge between the client and our APIs (We wan't that the client knows the real endpoint of the other services) . It can be the problem?
> 
> I'm going to add a dummy controller with the same route as appear in Upstream to test if in the swagger.json the path is generated.
> 
> I'll post the results later.
> 
> Thanks. ^_^

Hi again.

I've added a controller with the same route but it don't still appear in the swagger.json.

Back to the origins, I've tried to use the sample that appears in the "README.md" file of the project. But, surprise, it doesn't work too.

![image](https://user-images.githubusercontent.com/35351762/122187288-33d25680-ce8f-11eb-8779-1fea70272838.png)


In this time I've added an ocelot.json and change the code in my Program.cs
`.ConfigureAppConfiguration((hostingContext, config) =>
                 {
                     config
                     .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                     .AddJsonFile("ocelot.json", optional: false, reloadOnChange: true);
                     //.AddJsonFile("configuration." + hostingContext.HostingEnvironment.EnvironmentName.ToLower() + ".json", optional: false, reloadOnChange: true)
                     //.AddJsonFile("appsettings." + hostingContext.HostingEnvironment.EnvironmentName.ToLower() + ".json", optional: false, reloadOnChange: true);
                 });`


The Startup.cs file is the same as before. Sincerely, I don't know where is the problem

We have a problem with this api in our environment production and we want to include this swagger as "check" to verify that the api is really deployed in our production dockers.

What a pity!

Thanks

**Comment by cctron** [comment]
> Hi.
> One of the main features is the transformation of downstream documentation into upstream. Translation of paths, removal of paths that are not routed outside through ocelot, removal of unused components.
> 
> If you just want to publish the downstream documentation, you can set parameter `TransformByOcelotConfig` to `false`
> 
> ```json
>   "SwaggerEndPoints": [
>     {
>       "Key": "retrieve",
>       "TransformByOcelotConfig": false,
>       "Config": [
>         {
>           "Name": "RetrieveExpedientsGateway API",
>           "Version": "v1",
>           "Url": "https://localhost:5001/swagger/v1/swagger.json"
>         }
>       ]
>     }
>   ]
> ```
> 
> I hope this helps you.
> 
> I wish you have a nice day.

Sorry, I didn't refresh the page and I didn't see your reply. I'll try it

Give me 5 minutes ^_^

Thanks!

**Comment by cctron** [comment]
> > Hi.
> > One of the main features is the transformation of downstream documentation into upstream. Translation of paths, removal of paths that are not routed outside through ocelot, removal of unused components.
> > If you just want to publish the downstream documentation, you can set parameter `TransformByOcelotConfig` to `false`
> > ```json
> >   "SwaggerEndPoints": [
> >     {
> >       "Key": "retrieve",
> >       "TransformByOcelotConfig": false,
> >       "Config": [
> >         {
> >           "Name": "RetrieveExpedientsGateway API",
> >           "Version": "v1",
> >           "Url": "https://localhost:5001/swagger/v1/swagger.json"
> >         }
> >       ]
> >     }
> >   ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope this helps you.
> > I wish you have a nice day.
> 
> Sorry, I didn't refresh the page and I didn't see your reply. I'll try it
> 
> Give me 5 minutes ^_^
> 
> Thanks!

Now appears the swagger.json information

![image](https://user-images.githubusercontent.com/35351762/122190549-34202100-ce92-11eb-88f8-f0e0d1942918.png)

But it's true, my custom routes included in "configuration.development.json" (or ocelot.json, whatever) don't still appear as path and I can't explain it.

Our client is waiting for this solution in production, so I'll have to find another solution instead of use Ocelot Gateway :(

Thanks for your time.

I'm very appreciate it.

**Comment by Burgyn** [comment]
Thank you for the information.

Good luck
