### ISSUE TITLE
My Swagger.json default values for string are reverting to "string"

### ISSUE THREAD

**Issue by itservicesfisg** [Burgyn/MMLib.SwaggerForOcelot#182]
I have set a bunch of default values in my swagger.json for a specific service. When I run the service without the gateway all of the default values are honoured. When I run the service through the gateway the value is set at "string". It is picking up the rest of the swagger document. Just the default values are not set

I'm really rather hoping this is something stupid that I've done.

![image](https://user-images.githubusercontent.com/44289623/128540677-b636433f-543c-4edb-b5c8-0b4430b25fea.png)

Without the gateway
![image](https://user-images.githubusercontent.com/44289623/128540793-eea62378-f452-4896-80a3-69b0b33b0d57.png)

With the gateway
![image](https://user-images.githubusercontent.com/44289623/128540976-3d0c8d0a-7e52-4e64-9f97-93554ffa2a22.png)

**Comment by Burgyn** [comment]
Hi.  I am currently vacating.  I'll look into it next week.

**Comment by Burgyn** [comment]
Hi,

Can you please provide a demo project to further investigate this issue? (maybe part of source swagger.json will suffice)

Many thanks.
