### ISSUE TITLE
HttpClientFactory Dynamic Configuration

### ISSUE THREAD

**Issue by thomas-illiet** [Burgyn/MMLib.SwaggerForOcelot#189]
Hello Guys,

Many thanks for this project, can you implement the static or dynamic HttpClientFactory configuration in the following class ```DownstreamSwaggerDocsRepository``` ?

I need this to able to set the proxy configuration for backend API.

Thanks
Thomas

**Comment by Burgyn** [comment]
Hi,

Thank you for the suggestion. I'll look into it later this week.

**Comment by Burgyn** [comment]
Hi @thomas-illiet,

What exactly do you need to configure? Will it be enough if you can create your own `HttpClientHandler`?

For example, like this:
```csharp
services.AddSwaggerForOcelot(Configuration, (c) =>
{
    c.ConfigureHttpMessageHandler(()=> 
      new HttpClientHandler() { 
         Proxy = httpProxy 
      });
});
```
