### ISSUE TITLE
Renaming swagger gateway

### ISSUE THREAD

**Issue by Arcalise08** [Burgyn/MMLib.SwaggerForOcelot#193]
I'm unsure if this is a bug or if I'm simply using it wrong. 

I'm trying to change the default `/swagger` prefix

I've tried all combinations of the following
```
app.UseSwaggerForOcelotUI(opt =>
{
    //opt.DownstreamSwaggerEndPointBasePath = "/my-prefix";
    //opt.PathToSwaggerGenerator = "my-prefix";
    //opt.ServerOcelot = "/my-prefix";    
    opt.RoutePrefix = "/my-prefix";
});
```
the RoutePrefix option seems like the one to use.

And going to `localhost/my-prefix` will redirect to `localhost/my-prefix/index.html` like it should, but I get a 404 error.

**Comment by Burgyn** [comment]
Hi,

try to use property `RoutePrefix`

```csharp
app.UseSwaggerForOcelotUI(opt =>
{
    opt.RoutePrefix = "docs";
})
```

⚠ but be careful, no slash!
