### ISSUE TITLE
Array-parameter for GET query not work

### ISSUE THREAD

**Issue by zohanidze** [Burgyn/MMLib.SwaggerForOcelot#195]
Hi!
I have GET endpoint in origin API with array-parameter (filter): 
http://localhost:4999/api/User/GetUsers?filterId=1&filterId=2

And I have server-ocelot with proxying this endpoint:
http://localhost:4998/gateway/User/GetUsers?filterId=1&filterId=2

Route config:
`{
      "DownstreamPathTemplate": "/api/User/GetUsers",
      "UpstreamPathTemplate": "/gateway/User/GetUsers?filterId=1&filterId=2",
      "UpstreamHttpMethod": [
        "Get"
      ],
      "DownstreamScheme": "http",
      "Key": "users",
      "SwaggerKey": "users",
      "ServiceName": "users"
    }`

Endpoint in ocelot-swagger return 404 http-error with curl:
curl -X GET "http://localhost:4998/gateway/User/GetUsers?filterId%5B0%5D=1&filterId%5B1%5D=2" -H  "accept: text/plain"

**Comment by Burgyn** [comment]
Hi,

It appears that SwaggerUI cannot generate a request if the swagger definition for the endpoint contains query params in the parameters section as well as directly in the path.

As a workaround, you can use that you fill the given query parameters directly on SwaggerUI.

---

Note to me: A possible future solution would be to remove the query parameters in the documentation transformation if they are already in the path.
