### ISSUE TITLE
Update Swashbuckle NuGet packages from 5.6.3 to 6.2.3

### ISSUE THREAD

**Issue by bodnarkevin** [Burgyn/MMLib.SwaggerForOcelot#200]
Hi!

I was looking forward to using the Swagger UI's new [OpenID Connect Discovery](https://swagger.io/docs/specification/authentication/openid-connect-discovery/) functionality, however it is only supported from version Swagger UI v3.38.0, which is only supported by the 6.2.3 version Swashbuckle ([compatibility](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#compatibility)).

It would be a really useful feature, hopefully it is not too hard to update.

**Comment by Burgyn** [comment]
Closed by #201
