### ISSUE TITLE
Challange while using  MMLib.SwaggerForOcelot

### ISSUE THREAD

**Issue by balaramsathuluri** [Burgyn/MMLib.SwaggerForOcelot#202]
**Describe the bug**
I have below ASP.NET CORE web api micro services, As suggested in the documentation section I have added SwashBuckle.AspNetCore (6.2.3) to these micro services. 
1. Admin : attached image for startup, Program.cs
![Admin Service](https://user-images.githubusercontent.com/13834820/140034558-0ef47524-2602-4f53-9036-8613567d37e4.jpeg)
2. Document :  attached image for startup, Program.cs
![Document Service](https://user-images.githubusercontent.com/13834820/140034770-4aa3aa95-f581-4ee1-853b-46533798770e.jpeg)
One API Gateway Project called APIGateway. To this project I have added 
- Ocelot(17.0.0)
- MMLib.SwaggerForOcelot(4.4.3)
![API Gateway](https://user-images.githubusercontent.com/13834820/140035560-5ce3cce6-08bf-4b56-8355-3b360c3ed385.jpeg)

**Expected behavior**
Down Stream API"s are not loading
![Ocelot Swagger](https://user-images.githubusercontent.com/13834820/140036070-7259188b-bc78-45be-b66e-f791c9d53949.jpeg)

**To Reproduce**
If it is a possible attache:
1. Original downstream `swagger.json`.
2. Ocelot ReRoutes configuration.

Swagger.JSON
![Swagger](https://user-images.githubusercontent.com/13834820/140036495-88fec350-a969-4e01-b5b2-3cc6bc1bcc05.jpeg)
Ocelot.Development.Json
![Ocelot Developmet](https://user-images.githubusercontent.com/13834820/140036891-1a605a75-13c6-490f-b6d0-7fc46cfa7b4e.jpeg)

**Comment by balaramsathuluri** [comment]
Downstream Micro service API's are not loading in ocelot swagger UI. Please help on this

**Comment by Burgyn** [comment]
Hi,

It's look that you have different swagger key on Routes definition and in SwaggerEndPoints

![image](https://user-images.githubusercontent.com/5930822/140492296-8b72dbb0-76fe-4d5c-8e82-69652d36bdc0.png)

**Comment by balaramsathuluri** [comment]
Thank You Burgyn for quick response. 
As suggested I have changed the key in Swagger EndPoint to "Admin". I could see the API's in gate way now related to Admin only.

But when I try to load Document API's in using drop down I am getting below response.

**Comment by Burgyn** [comment]
I am after appendix surgery.  I'll look into it when I get back from the hospital.

**Comment by balaramsathuluri** [comment]
I have updated both Routes and EndPoints to have Down stream API's related to Document API's as well, not sure why it is giving "No Operation defined in spec"
![Documents-Swagger](https://user-images.githubusercontent.com/13834820/140700194-c1d4d3fd-b587-466a-b00d-37e99dc7a978.jpeg)

Here is the ocelot.json file.
                                                                                                                                                                                                                                                                                                                                                                                                                                  
![Ocelot Development-json](https://user-images.githubusercontent.com/13834820/140702287-48cce636-3e56-40ff-ab9b-d9b8fa329efa.jpeg)

Here is the Startup.cs for Document API



![Startup-cs](https://user-images.githubusercontent.com/13834820/140703124-350faf7f-5b1b-463f-a2d8-5aa947b00662.jpeg)

**Comment by balaramsathuluri** [comment]
Thanks.
    On Monday, 8 November, 2021, 01:17:25 pm IST, Miňo Martiniak ***@***.***> wrote:  
 
 


I am after appendix surgery. I'll look into it when I get back from the hospital.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Burgyn** [comment]
Hi, 
please can you attach your Document API swagger docs?

thanks.

**Comment by kyrvlasiuk** [comment]
![Screenshot 2021-11-25 134939](https://user-images.githubusercontent.com/42720377/143436750-42ed86ef-b218-4b55-b30e-f6919c1bb68a.png)
Hi, @balaramsathuluri 

As far as I gather this error is for all SwaggerEndPoints items whose Key does not have an exact match in Routes section under SwaggerKey. You correctly identified and fixed error for "Process" but did not do the same for "documents" whose nearest match in Routes  is "Document" which is not the same. 

Hope it helps
