### ISSUE TITLE
Different gateway swagger response json than service swagger

### ISSUE THREAD

**Issue by teomane** [Burgyn/MMLib.SwaggerForOcelot#203]
Hello,

I have an issue with the library. The example value of the response of a service is seen differently on the gateway swagger. Let me give an example:

This is the JSON of the response of my endpoint (taken from the service's swagger):
```
[
  {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "isRejected": true,
    "category": {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "parentCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "code": "string",
      "name": "string",
      "level": 0,
      "parentCategory": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "parentCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "code": "string",
        "name": "string",
        "level": 0
      }
    }
  }
]
```

And this is the JSON from the gateway for the same service:
```
[
  {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "isRejected": true,
    "category": {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "parentCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "code": "string",
      "name": "string",
      "level": 0
    }
  }
]
```

I can't see the node:
```
"parentCategory": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "parentCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "code": "string",
        "name": "string",
        "level": 0
}
```

What do you think about the problem ?

**Comment by Burgyn** [comment]
Hi,

it's from Ocelot Aggregates, or from standard service? If its from aggregation then looks similar like issue #191

**Comment by teomane** [comment]
It is not from aggregates. It is just a standard downstream service configured with Routes.

**Comment by Burgyn** [comment]
Can you please prepare simple reproducible example. Because it's OK on my projects.

**Comment by eymentopcuoglu** [comment]
Hi,

It seems rendering of circular-referenced objects on Swagger UI is still an ongoing [issue](https://github.com/swagger-api/swagger-ui/issues/3325). However, a [comment](https://github.com/swagger-api/swagger-ui/issues/3325#issuecomment-662030081) on this issue seemed to work for me! For our case, to make the paths of the downstream Swagger endpoints relative, I used `DownstreamSwaggerEndPointBasePath`:

```CSharp
app.UseSwaggerForOcelotUI(opt =>
            {
                opt.DownstreamSwaggerEndPointBasePath = "../swagger/docs";
            });
```

**Comment by teomane** [comment]
Thank you @eymentopcuoglu. It works for me.
