### ISSUE TITLE
Add OAuthClientId and other OAuth options

### ISSUE THREAD

**Issue by ptrushin** [Burgyn/MMLib.SwaggerForOcelot#208]
In Swashbuckle I can set OAuthClientId for Authorize like
`app.UseSwaggerUI(opt =>
            {
                opt.OAuthClientId("ffff");
            });`
In case of Ocelot OAuthClientId different for other services.
Can you add this option in config file for service like
`"Key": "api",
            "Config": [
                {
                    "Name": "name",
                    "Version": "v1",
                    "Url": "https://..../api/swagger.json",
                    "OAuthClientId": "clientId"
                }
            ]`

**Comment by Burgyn** [comment]
Hi @ptrushin,

Can you please be more specific? Please describe your idea better. 
Well thank you.
