### ISSUE TITLE
Ocelot configuration been re-write after IIS pool idle timeout

### ISSUE THREAD

**Issue by nikolay-dimitrov** [Burgyn/MMLib.SwaggerForOcelot#217]
Hello everyone
Im facing really strange behaviour from Ocelot  while im using the great feature for merging multiple configuration files and using the Swagger

1) After Ocelot is been deployed and started(on IIS) for first time is creating automatically ocelot.Production.json file which has exactly the same configurations like ocelot.json file(this file is again created on first start of the application and its contains the merge result of my sub-configurations files) - is there a way Ocelot not to create ocelot.Production.json. Just as remark the Gateway is running on this moment without any problems no matter of the fact that both files (ocelot.Production.json and ocelot.json are exactly the same). Additional remark here is that configurations provided inside ocelot.SwaggerEndPoints.json ARE NOT presented in both ocelot.Production.json and ocelot.json.
 
2) After the IIS pool idle timeout and durring the next request for some reason Ocelot is re-building the ocelot.Production.json and ocelot.json BUT this time it start to return and error that there are duplicated Routes - extremely strange because the files again contains the same configurations the only differences is that this time in ocelot.json configurations from ocelot.SwaggerEndPoints.json are presented

3) If we are using Administration API to change the configurations on run time and then leave the IIS pool idle timeout on the next request ocelot is will merge again all sub-configurations files which is resulting that changes made from Administration API are deleted

Does any one face this as a problems and if its possbile to provide some guidelines

         public class Program
          {
              public static void Main(string[] args)
              {
                  CreateHostBuilder(args).Build().Run();
              }
              public static IHostBuilder CreateHostBuilder(string[] args) =>
                    Host.CreateDefaultBuilder(args)
                       .ConfigureWebHostDefaults(webBuilder =>
                       {
                           webBuilder.ConfigureAppConfiguration((hostingContext, config) =>
                             {
                                 config
                                      .SetBasePath(hostingContext.HostingEnvironment.ContentRootPath)
                                      .AddJsonFile("appsettings.json", true, true)
                                      .AddJsonFile("appsettings.Dev.json", true, true)
                                      .AddJsonFile("appsettings.Stage.json", true, true)
                                      .AddJsonFile("appsettings.Test.json", true, true)
                                      .AddJsonFile("appsettings.Prod.json", true, true)
                                      .AddJsonFile("ocelot.json", true, true)
                                      .AddJsonFile("ocelot.SwaggerEndPoints.json", true, true)
                                      .AddOcelotWithSwaggerSupport((o) => {
                                          o.FileOfSwaggerEndPoints = "ocelot.SwaggerEndPoints";
                                          //o.Folder = "Configuration";
                                          //o.HostEnvironment = hostingContext.HostingEnvironment;
                                      })
                                     .AddEnvironmentVariables();
      
                             }).UseStartup<Startup>();
      
                       });
          }

          public class Startup
              {
                  public Startup(IConfiguration configuration)
                  {
                      Configuration = configuration;
                  }
          
                  public IConfiguration Configuration { get; }
          
                  // This method gets called by the runtime. Use this method to add services to the container.
                  public void ConfigureServices(IServiceCollection services)
                  {                   
                      services.AddControllers();
                      services.AddOcelot().AddAdministration(Configuration["DCPAPIGatewayAdministrationPath"], Configuration["DCPAPIGatewayAdministrationClientSecret"]);
                      services.AddSwaggerForOcelot(Configuration);
                      services.AddSwaggerGen(c =>
                      {
                          c.SwaggerDoc("v1", new OpenApiInfo { Title = "DCP Gateway", Version = "v1" });
                      });
          
                  }
          
                  // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
                  public async void Configure(IApplicationBuilder app, IWebHostEnvironment env)
                  {
                      if (env.IsDevelopment())
                      {
                          IdentityModelEventSource.ShowPII = true;
                          app.UseDeveloperExceptionPage();
                      }
                      app.UseSwagger();
                      await app.UseSwaggerForOcelotUI(opt =>
                      {
                          opt.PathToSwaggerGenerator = "/swagger/docs";
                      }).UseOcelot();
                      app.UseHttpsRedirection();
          
                      app.UseRouting();
          
                      app.UseAuthorization();
          
                      app.UseEndpoints(endpoints =>
                      {
                          endpoints.MapControllers();
                      });
                  }
              }

**Comment by Burgyn** [comment]
Hi @nikolay-dimitrov,

implementation is the same as in the Ocelot project. So it is likely that it is not related to this library.

From Ocelot documentation:
> In this scenario Ocelot will look for any files that match the pattern (?i)ocelot.([a-zA-Z0-9]*).json and then merge these together. If you want to set the GlobalConfiguration property you must have a file called ocelot.global.json.
>
> The way Ocelot merges the files is basically load them, loop over them, add any Routes, add any AggregateRoutes and if the file is called ocelot.global.json add the GlobalConfiguration aswell as any Routes or AggregateRoutes. Ocelot will then save the merged configuration to a file called ocelot.json and this will be used as the source of truth while ocelot is running

So, your origin files as `ocelot.production,json` are not deleted and still exist (this file is not add to configuration builder). 
- Please check if your project contains `ocelot.json`,if so, remove it. 

Point 3. - Unfortunately, I don't think it's possible to use the Administration API correctly in the current implementation
