### ISSUE TITLE
Operation Filter Feature

### ISSUE THREAD

**Issue by MaximilianoCovela** [Burgyn/MMLib.SwaggerForOcelot#219]
Hi! 
I couldn't find a way to replicate the "OperationFilter" that can be used in the original Swagger. 

My objective was from there to add a custom header to all the methods that the Swagger shows, since then with an ocelot delegating handler I validate the value of that additional header.

Maybe it would be nice if there is something that can be used like what I show in the screenshot (source: https://alexdunn.org/2018/06/29/adding-a-required-http-header-to-your-swagger-ui-with-swashbuckle/). Thank you very much!

![image](https://user-images.githubusercontent.com/57292421/152154416-a1fd54a8-90d0-453a-ad31-9c0676a85153.png)

**Comment by Burgyn** [comment]
Hi,

unfortunately this package does not directly support it. This package does not generate swagger documentation _(except for aggregation documentation)_, it only downloads downstream service documentation _(removes unused components, paths, and renames routes by ocelot configuration)_ and provides it to the client. So `OperationFilter` will not be used.

You can use `ReConfigureUpstreamSwaggerJson` delegate and add these headers in your own way.

```csharp
public string AlterUpstreamSwaggerJson(HttpContext context, string swaggerJson)
{
  var swagger = JObject.Parse(swaggerJson);
  // ... alter upstream json
  return swagger.ToString(Formatting.Indented);
}

app.UseSwaggerForOcelotUI(opt => {
  opt.ReConfigureUpstreamSwaggerJson = AlterUpstreamSwaggerJson;
});
```

**Comment by MaximilianoCovela** [comment]
Hi, that served me for what I needed. Very useful package, thank you very much for your help!

**Comment by Burgyn** [comment]
Hi,

glad to hear that I helped.
