### ISSUE TITLE
Multiple Configuration Files

### ISSUE THREAD

**Issue by eymentopcuoglu** [Burgyn/MMLib.SwaggerForOcelot#222]
Hi,

Since Ocelot does not consider `SwaggerEndPoints` and `SwaggerKey` [while deserializing configuration files](https://github.com/ThreeMammals/Ocelot/blob/36ad6e1e7873526e28300c7ac6312052f6df14e9/src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs#L65), the produced [`ocelot.json` file](https://github.com/ThreeMammals/Ocelot/blob/36ad6e1e7873526e28300c7ac6312052f6df14e9/src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs#L78) does not contain these fields, resulting with the loss of SwaggerForOcelot configuration in any of these files. 

Do you have any suggestions about working with multiple configuration files? 

Thank you!

**Additional context**
[Merging configuration files](https://ocelot.readthedocs.io/en/latest/features/configuration.html#merging-configuration-files)

**Comment by Burgyn** [comment]
Hi @eymentopcuoglu 

Please check [Merging configuration files](https://github.com/Burgyn/MMLib.SwaggerForOcelot#merging-configuration-files) section in Readme file.

**Comment by eymentopcuoglu** [comment]
I had missed it, thank you very much!
