### ISSUE TITLE
Custom Documentation Layout

### ISSUE THREAD

**Issue by zolaikhahammad** [Burgyn/MMLib.SwaggerForOcelot#227]
I want to add custom layout to my SwaggerUI for Ocelot. Can someone please guide how we can use this feature in MMLib.SwaggerForOcelot. 

e.g I want to show the api endpoints in a tab not in the dropdown or in a menu. Inject custom css.

**Comment by Burgyn** [comment]
Hi.  

This project uses the standard Swashbuckle project to generate SwaggerUI.  So it should be possible to adapt.  I've never tried it, but I think it's possible. For example try this  https://link.medium.com/xejrJGnAppb
