### ISSUE TITLE
How to show Gateway as first and select by default

### ISSUE THREAD

**Issue by P9avel** [Burgyn/MMLib.SwaggerForOcelot#235]
Hi, i am want to do as on screenshot. How to do this?
![image](https://user-images.githubusercontent.com/95086762/182844321-cae71a7e-e421-4956-9570-555efe50a6bb.png)

**Comment by Burgyn** [comment]
Hi @P9avel ,

Please check this section in documentation https://clicks.burgyn.online/rreaaMwPD

**Comment by P9avel** [comment]
I am read before. o.GenerateDocsForGatewayItSelf = true; added Gateway item as last in my case as last item in combobox  and Swagger selected first item (not gateway) by default.

**Comment by Burgyn** [comment]
Hi, sorry, I didn't understand that you were talking about order.

Unfortunately, there is no option to change the order.

If you need it, you can prepare a pull request.
