### ISSUE TITLE
[Question] SwaggerEndpoints configurations per enviroment 

### ISSUE THREAD

**Issue by maxoizs** [Burgyn/MMLib.SwaggerForOcelot#238]
I have a question  regarding SwaggerEndpoints, I'm using ocelot and swagger for ocelot, with configuration folder and so far it works fine, the issue is, in SwaggerEndpoint how do I mention that base URL should change per environment, I've it fixed for dev environment now, but I would like to push to qa and stage as well. 
so ocelot.swaggerendpoints.json like that 
```
{
  "SwaggerEndPoints": [
    {
      "Key": "ProductService",
      "Config": [
        {
          "Name": "Product Service",
          "Version": "v1",
          "Url": "https://service-dev.net/swagger/v1/swagger.json"
        }
      ]
    }
   ]
}
```
example I would like to be in QA environment like this https://service-qa.net/swagger/v1/swagger.json and stage https://service-stage.net/swagger/v1/swagger.json etc 

do you guys add multi configs for all environments or do change that file on pipeline using yaml or do you override from code and how, or does the global configuration for ocelot work and how please ?

**Comment by Burgyn** [comment]
Hi @maxoizs,

for these purposes I use the [Service discovery](https://ocelot.readthedocs.io/en/latest/features/servicediscovery.html), especially [AppConfiguration](https://github.com/Burgyn/MMLib.Ocelot.Provider.AppConfiguration) _(different `appsettings.json` for different environments)_.

SwaggerForOcelot can read documentation from services defined in by that providers. [See documentation](https://github.com/Burgyn/MMLib.SwaggerForOcelot#service-discovery).

**Comment by maxoizs** [comment]
@Burgyn thanks a lot , AppConfiguratoin as a service discovery worked very well so far, and appSettings is much easier to configure per environment especially  that we were using docker, and replace a token within a docker image was a nightmare for me 😄 , thanks a lot for that.

**Comment by Burgyn** [comment]
I'm glad I could help
