### ISSUE TITLE
UpstreamHttpMethod ignored

### ISSUE THREAD

**Issue by kmaesdillen** [Burgyn/MMLib.SwaggerForOcelot#25]
**Describe the bug**
When UpstreamHttpMethod is used in the ocelot configuration.json the generated swagger.json will still have all endpoints present even when the HttpMethod was not present in the UpstreamHttpMethod

**Expected behavior**
Method for which the HttpMethod is not present in the configuration.json should not be in the generated swagger.

**To Reproduce**
create an api with a simple endpoint with a GET and POST method
create a ocelot configuration.json for these endpoints with UpstreamHttpMethod: ["GET"]
I have checked it with version 1.1.0 and 1.2.0. Both have the problem.

**Comment by Burgyn** [comment]
Thanks for your report.
I reproduced it.
I'll try to fix it today or tomorrow.

**Comment by Burgyn** [comment]
I released new version `1.2.1` where is this bug fixed. This version will be listed in [nuget.org](https://www.nuget.org/packages/MMLib.SwaggerForOcelot/1.2.1) in a few minutes.
