### ISSUE TITLE
Documentation -> o.GenerateDocsForGatewayItSelf

### ISSUE THREAD

**Issue by fischer7** [Burgyn/MMLib.SwaggerForOcelot#261]
**Describe the bug**
That's actually a problem at you documentation.  Header: ``The Gateway documentation itself``
```services.AddSwaggerForOcelot(Configuration,
  (o) =>
  {
      o.GenerateDocsForGatewayItSelf(opt =>
...
```

erro: ``Non-invocable member 'OcelotSwaggerGenOptions.GenerateDocsForGatewayItSelf' cannot be used like a method.`` 

**Expected behavior**
Change ``GenerateDocsForGatewayItSelf`` to ``GenerateDocsDocsForGatewayItSelf``

Thanks for such great lib!

**Comment by Burgyn** [comment]
Hi thans for your issue.

Fixed!
