### ISSUE TITLE
How to set base path for swagger.json

### ISSUE THREAD

**Issue by rkoczen** [Burgyn/MMLib.SwaggerForOcelot#27]
**Describe the bug**
Swagger documentation is not accessible  if we deploy APIs using path for example:

http://url/gateway/swagger

is unable to find docemtation located on two api at below url:

http://url/ap1/
http://url/ap2/

**Expected behavior**
can work using path not only ports for specific api

**Comment by rkoczen** [comment]
Hi The problem is here:

If we assign here options.EndPointBasePath in method UseSwaggerForOcelot like this "/swagger/docs"

and we use basePath in AddSwaggerEndPoints from config EndPointBasePath like "/gateway/swagger/docs"

everything works completly fine.

You can accesS both swagger documentation.

Is it possible to add additional endpoint for mapping ?

 private static void UseSwaggerForOcelot(IApplicationBuilder app, SwaggerForOcelotUIOptions options)
            => app.Map(options.EndPointBasePath, builder => builder.UseMiddleware<SwaggerForOcelotMiddleware>(options));

        private static void AddSwaggerEndPoints(SwaggerUIOptions c, IEnumerable<SwaggerEndPointOptions> endPoints, string basePath)
        {
            foreach (var endPoint in endPoints)
            {
                foreach (var config in endPoint.Config)
                {
                    c.SwaggerEndpoint($"{basePath}/{config.Version}/{endPoint.KeyToPath}", $"{config.Name} - {config.Version}");
                }     
            }
        }

**Comment by Burgyn** [comment]
Hi,
thank you for reporting the problem and for research.
Can you provide an example of how you would like to use it?

Or ideal make PR if you know how to implement it. (Contribution is open ☺️)

**Comment by rkoczen** [comment]
Great 😀

I ll try do it tommorow 😀 it will be helpful i think if You can Creat
nuget with fixed of course after review my pull request 😀

Rafał

W dniu śr., 5.06.2019 o 18:50 Miňo Martiniak <notifications@github.com>
napisał(a):

**Comment by Burgyn** [comment]
Great.

Of course, when you implement it (maybe I'll make some corrections 😉), then I will release new version to nuget.

Thanks a lot.

**Comment by rkoczen** [comment]
Of course 😀

W dniu śr., 5.06.2019 o 19:04 Miňo Martiniak <notifications@github.com>
napisał(a):

**Comment by rkoczen** [comment]
It looks I don't have rights to push my branch

**Comment by Burgyn** [comment]
Yes. You must creat in your fork. And then creat PR.

**Comment by rkoczen** [comment]
Sorry but I have still problem with ssh i don't have any idea :(

Could I send You solution by email or etc ?

**Comment by Burgyn** [comment]
Hello,
The standard way to contribute to OpenSource on GitHub is as follows:

1. Create a fork to your repository.
2. Implement your changes in the new branch.
3. Push changes to your origin.
4. Create PR.

If you have problem with creating PR from your repo, than send me link to your fork.

**Comment by rkoczen** [comment]
But i have problem with public Saj key 😀

W dniu czw., 6.06.2019 o 11:27 Miňo Martiniak <notifications@github.com>
napisał(a):

**Comment by Burgyn** [comment]
OK, but it strange.

Can you upload your solution somewhere and send me a link for it?

**Comment by rkoczen** [comment]
http://www.common-soft.pl/MMLib.SwaggerForOcelot.rar

I am fighting for few hours with this ssh, and i do'nt have solution yet:(

maybe quicker be like this.

Please let me know what You think.

**Comment by Burgyn** [comment]
Hi, I created PR #29, where I implement your changes. (I changed it a bit, because of better understanding)

Please check it, if you are ok with these.


---
I don't understand why you have a problem with SSH when you push to your repository. Are you sure you are pushing changes to your fork?

**Comment by rkoczen** [comment]
Its look great:)

About SSH i don't have any idea, i need check my whole computer.

**Comment by Burgyn** [comment]
I released new version. New version will be availabe in few minutes in https://www.nuget.org/packages/MMLib.SwaggerForOcelot/1.3.0

Thanks a lot

**Comment by Arslan-Munir** [comment]
It has been great to work with Ocelot and swagger.
But here is a strange behavior I am getting.
When I use app.UseSwaggerForOcelotUI with opts.SwaggerEndpoint, it duplicates the swagger documentation for each down services. 

I can also integrate down services swagger directly by using app.UseSwaggerUI with SwaggerEndpoint. Here I don't need any configuration and no need of app.UseSwaggerForOcelotUI

![1](https://user-images.githubusercontent.com/46858790/69417412-6ca15c80-0d3a-11ea-8c68-24c5c1db61dd.jpg)
![2](https://user-images.githubusercontent.com/46858790/69417428-762ac480-0d3a-11ea-8e92-5d0be6d3c5e3.jpg)

Can anyone please tell me what is the right way to get the down services documentation?

**Comment by Burgyn** [comment]
Hi @Arslan-Munir,
Sorry, I'm outside of computer (vacation with family). I'll look at it when I get back.

Please, can you create new issue for this?
Thanks.

**Comment by Arslan-Munir** [comment]
Hi @Burgyn 
Sure I will create this as a new issue.
Thanks.
