### ISSUE TITLE
Could not resolve reference

### ISSUE THREAD

**Issue by walidaziz** [Burgyn/MMLib.SwaggerForOcelot#35]
**Describe the bug**
Hi,
Through Ocelot some references could not be resolved.
In the following sample TypeColors or TypeImages are not retrieved in (POST)/api/admin/settings 

They does existe in original JSON but not in ocelot json

[ocelot.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/3355068/ocelot.txt)
[swagger.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/3355069/swagger.txt)

Thanks

**Comment by Burgyn** [comment]
Hi,
this bug fix is deployed in [version `1.4.1` .](https://www.nuget.org/packages/MMLib.SwaggerForOcelot/1.4.1)

**Comment by walidaziz** [comment]
Great ! Thanks. We will test that.
