### ISSUE TITLE
Good Job

### ISSUE THREAD

**Issue by balarvs2002** [Burgyn/MMLib.SwaggerForOcelot#38]
it is really very useful. Why dont you raise PR to https://github.com/ThreeMammals/Ocelot, So that It can be used by all.

**Comment by Burgyn** [comment]
Hi,
thanks. I am glad that this project is also useful for others.

I admit that I did not think about incorporating it into the original Ocelot repository. But it sounds like a good idea. Sometime in the future I may try.

**Comment by balarvs2002** [comment]
Thanks @Burgyn .  Looking forward to integrate with OCELOT
