### ISSUE TITLE
Support for local swagger

### ISSUE THREAD

**Issue by ianmccaul** [Burgyn/MMLib.SwaggerForOcelot#46]
In certain situations where a developer is slowly transitioning from a monolithic system they may have a hybrid gateway. So in some cases the gateway may have some local endpoints its serving as well as acting as a gateway for other services with ocelot. Would be nice if there was a way to be able to serve up the local swagger doc as well as the swagger docs of the downstream services.

**Comment by Burgyn** [comment]
Hello,

can you provide your suggestion on how it could be used?

Thanks.

**Comment by ianmccaul** [comment]
Not quite sure what you mean. As in how its used, the gateway swagger could list the local endpoints that still exist in the gateway, and are configured normally through starup, while having the remote endpoints listed in the drop down which are configured based on the ocelot.json.

**Comment by Burgyn** [comment]
Okay, I'm starting to understand.
It's a nice improvement. Currently I do not have the time for it. However, the contributions is open. You can send your PR.

**Comment by Burgyn** [comment]
Hi,

this feature was implemented in PR #89.

Is released as version `2.0.0-alpha.3`
