### ISSUE TITLE
Update configuration via Ocelot.Administration

### ISSUE THREAD

**Issue by ChrisSwinchatt** [Burgyn/MMLib.SwaggerForOcelot#47]
**Is your feature request related to a problem? Please describe.**

We are moving to dynamic configuration of Ocelot via a fairly hacky method that (edit: used to) involves POSTing the new configuration to the Ocelot administration API. However, SwaggerForOcelot:

1. Throws because there are no Swagger documents in the startup config, and
2. (I presume) does not react to Ocelot configuration updates.

**Describe the solution you'd like**

It would be good if SwaggerForOcelot:

1. Did not crash the program if there were no configured Swaggers, and
2. Updated itself when the Ocelot configuration changes.

This might require changes to Ocelot to make it issue an event or trigger a change token of some kind. I'll investigate this myself when I get the time, probably this or next week. Please let me know if you have any concerns.

Chris

**Comment by Burgyn** [comment]
Hi,
thanks for your issue.

If you have time to explore, I would be glad if you take a look at it.

Thanks.

**Comment by Burgyn** [comment]
Hi,
is there something new?

**Comment by ChrisSwinchatt** [comment]
Hi @Burgyn - Apologies for late response. It looks like the necessary changes to Ocelot will go ahead fairly soon, so provided I don't get dragged away again, I'll get onto this as soon as my pull request over there goes through.

**Comment by Burgyn** [comment]
Hi @ChrisSwinchatt,
thanks for information.

Good luck.

**Comment by Burgyn** [comment]
Hi,
is there something new?
