### ISSUE TITLE
Found SwaggerJsonTransformer of low performance

### ISSUE THREAD

**Issue by yoli799480165** [Burgyn/MMLib.SwaggerForOcelot#52]
**Describe the bug**
 SwaggerJsonTransformer has performance problems.

**Expected behavior**
The size of swagger.json in api project more than 1MB, and request took more than 15 seconds.

**To Reproduce**
Request:
![001](https://user-images.githubusercontent.com/4556286/67466729-26dd6f80-f67a-11e9-9666-d4d143eaa363.png)
dotTrace:
![002](https://user-images.githubusercontent.com/4556286/67466778-3b216c80-f67a-11e9-862c-ff43ced4a682.png)

**Comment by Burgyn** [comment]
Hi,
thanks for your report.
At first glance it looks like jpath query.

Bad news: without refactoring actual implementation (geting rid of jpath) it doesn't make a sence.
Good news: next month I plan refactor this project. So next month I can fixed it.

I appologise for complication.

**Comment by Burgyn** [comment]
Hi,

please can you try version `1.10.4`? This version reduce time of 40%. Unfortunately now, I can't getting rid of `jpath`. 

Please can you provide your large `swagger json` file and `ocelot` configuration for the future investigation?

thanks a lot.
