### ISSUE TITLE
The scheme is duplicated.

### ISSUE THREAD

**Issue by xsilviox** [Burgyn/MMLib.SwaggerForOcelot#53]
The schema is duplicated. I tried it with http and https. I can not find the problem.
![schema](https://user-images.githubusercontent.com/13439465/67653985-38f63100-f94c-11e9-9e8a-2452318dd7ea.png)

**Comment by kajbonfils** [comment]
I have the same issue, running version 1.9.0. Could this be related to #51 ?

**Comment by kajbonfils** [comment]
> u

I just downgraded to v. 1.8.0, and the problem is removed.

`{
  "ReRoutes": [            
    {
      "UpstreamPathTemplate": "/services/Crm/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post" ],
      "DownstreamPathTemplate": "/api/v1/Crm/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 54199
        }
      ],
      "SwaggerKey": "CRMApi"
    }
  ],
  "SwaggerEndpoints": [    
    {
      "Key": "CRMApi",
      "Config": [
        {
          "Name": "CRM Api",
          "Version": "v1",
          "Url": "http://localhost:54199/swagger/v1/swagger.json"
        }
      ]
    }
  ],
	"GlobalConfiguration": {
		"BaseUrl":  "http://localhost:5051"
	}
}
`

**Comment by xsilviox** [comment]
Perfect thank you. With version 1.8 it works for me too.

**Comment by Burgyn** [comment]
Hi @xsilviox 

Please can you provide `ocelot.json` configuration and `swagger.json` of downstream service?

Thanks.

**Comment by mourier** [comment]
Having same issue - normal posting works fine tho.
So guess this is only an issue in the swagger part.

**Comment by Burgyn** [comment]
Hi @mourier

Please can you provide ocelot.json configuration and swagger.json of downstream service?

Thanks.

**Comment by mourier** [comment]
[https://gist.github.com/mourier/14415f1d9b71643de0de98869e9d6e0e](ocelot.json)
[https://gist.github.com/mourier/8ff7531c9ca452a25eb59d7fc3e98b5c](swagger.json)

**Comment by Burgyn** [comment]
Hi,
thanks for your reports and aditional informations.
It helped me reproduce this problem.

I'll fix it in next release `v2.0`. After finished issue #56.

As a workaround you can downgrade to version `1.8`

Thank you and apologize.

**Comment by Burgyn** [comment]
Fixed in version 1.10.2

**Comment by ThiyagarajanVellaichamy** [comment]
Hi Could you please help me out?
![Screenshot 2020-05-03 at 11 22 21](https://user-images.githubusercontent.com/63137672/80905510-9a022580-8d30-11ea-9ccf-4c3b0d1d85e6.png)

**Comment by Burgyn** [comment]
Hi @ThiyagarajanVellaichamy,
Pleaae, Can you create new issue for it an provide `ocelot.json`. 

Thanks.

**Comment by ThiyagarajanVellaichamy** [comment]
> Hi @ThiyagarajanVellaichamy,
> Please, Can you create new issue for it an provide `ocelot.json`.
> 
> Thanks.

{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/auth-service/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post" ],
      "SwaggerKey": "authswagger",
      "VirtualDirectory": "/authswagger"
    }
  ],
  "SwaggerEndPoints": [
    {
      "Key": "gateway",
      "TransformByOcelotConfig": false,
      "Config": [
        {
          "Name": "Gateway",
          "Version": "v1",
          "Url": "https://localhost:5003/swagger/v1/swagger.json"
        }
      ]
    },
    {
      "Key": "authswagger",
      "Config": [
        {
          "Name": "Authentication API",
          "Version": "v1",
          "Url": "https://localhost:5001/api/swagger/v1/swagger.json"
        }
      ]
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "https://localhost"
  }
 }
