### ISSUE TITLE
Swagger documentation become duplicated for each down services.

### ISSUE THREAD

**Issue by Arslan-Munir** [Burgyn/MMLib.SwaggerForOcelot#58]
Hi.
In swagger for ocelot, I observe a strange behavior.
When I use app.UseSwaggerForOcelotUI with opts.SwaggerEndpoint, it duplicates the swagger documentation for each down services. I can't figure it out, why this is happening? Am i doing something wrong?

Here is one more thing I would like to ask. I am able to integrate down services swagger documentation directly in my ocelot gateway just by using app.UseSwaggerUI with SwaggerEndpoint. Here I don't need any configuration and no need of app.UseSwaggerForOcelotUI.
Then why we are using this separate NuGet package?
![1](https://user-images.githubusercontent.com/46858790/69957604-cd901800-1524-11ea-9413-11e320d3da53.jpg)
![2](https://user-images.githubusercontent.com/46858790/69957605-cd901800-1524-11ea-8b8e-c9f7555da2f6.jpg)

**Comment by Burgyn** [comment]
Hi,
### First

The recommended way to use this library is as follows:

1. Configure SwaggerForOcelot in `ocelot.json`.

E.g.
```Json
 "SwaggerEndPoints": [
    {
      "Key": "Api1",
      "Config": [
        {
          "Name": "Service api 1",
          "Version": "v1",
          "Url": "http://localhost:5100/swagger/v1/swagger.json"
        }
      ]
    },
    {
      "Key": "Api2",
      "Config": [
        {
          "Name": "Service api 2",
          "Version": "v1",
          "Url": "http://localhost:5200/swagger/v1/swagger.json"
        }
      ]
    }
  ]
```

2. Fill `SwaggerKey` property on your rerout configuration.

E.g.
```Json
{
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5100
        }
      ],
      "UpstreamPathTemplate": "/api/contacts/{everything}",
      "UpstreamHttpMethod": [ "Get" ],
      "SwaggerKey": "api1"
    }
```

3. In the `ConfigureServices` method of `Startup.cs`, register the SwaggerForOcelot generator.
```CSharp
  services.AddSwaggerForOcelot(Configuration);
```

4. In `Configure` method, insert the `SwaggerForOcelot` middleware to expose interactive documentation.

```CSharp
       app.UseSwaggerForOcelotUI(Configuration);
```

> :warning: Don't use `opts.SwaggerEndpoint(...)` methods. Theses methods come from base class. My bad design, in next version will be removed.

When you will follow this, then swagger documentation be accessible via ocelot. 

### Second

Benefits of this package:
1. Easier to use. Based on configurations.
2. Addresses and paths are transform based on ocelot configuration

E.g.
If your upstream template looks like `"UpstreamPathTemplate": "/api/contacts/{everything}"` but downstream is `"DownstreamPathTemplate": "/api/{everything}"`, then swagger documentation generated by this package contains correct paths `/api/contacts/{everything}`.

3. Generated swagger contains only filtered endpoints based on ocelot configuration.
E.g. in many cases you don't want expose all downstream endpoints via ocelot to client. So this package filter that.

4. ...

---
I hope I helped you.

**Comment by Arslan-Munir** [comment]
Hi @Burgyn 
First of all, sorry for being too late. 
Thank you for your time & helpful comment.
It helps & the issue is resolved. :)

**Comment by Burgyn** [comment]
Hi @Arslan-Munir ,

you are welcome.
