### ISSUE TITLE
Customizable swagger base URL.

### ISSUE THREAD

**Issue by aspramsh** [Burgyn/MMLib.SwaggerForOcelot#60]
HI @Burgyn.

I have a question. Does Swagger for Ocelot support changing default swagger path? I need to use RoutePrefix from UseSwaggerUI method: 
`
app.UseSwaggerUI(c =>
{

    c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");

    c.RoutePrefix = "docs";
`});``

**Comment by Burgyn** [comment]
Hi @aspramsh 

Yes, SwaggerForOcelot package allow changing swagger documentation page default path.

```CSharp
app.UseSwaggerForOcelotUI(Configuration, opt =>
{
    opt.RoutePrefix = "docs";
});
```

**Comment by aspramsh** [comment]
Thank you.

**Comment by Burgyn** [comment]
You are welcome.
