### ISSUE TITLE
Configuration for bearer token.

### ISSUE THREAD

**Issue by aspramsh** [Burgyn/MMLib.SwaggerForOcelot#61]
Hi @Burgyn. I would like to know is there any specific config for adding bearer token to swagger for ocelot DownstreamSwaggerHeaders? I mean how to provide "Auth-Key", "AuthValue"?

**Comment by Burgyn** [comment]
Hi @aspramsh,
no special configuration exist.

This package only allows you to define the headers to be added directly in the code. (this settings is common to all request).
You have to do it yourself.

For example:
```CSharp
var headers = Configuration.GetSection("Headers").Get<Dictionary<string, string>>();

app.UseSwaggerForOcelotUI(Configuration, opt =>
{
    opt.DownstreamSwaggerHeaders = headers;
})
.UseOcelot()
.Wait();
```

```Json
"Headers": { "Auth-Key": "AuthValue" }
```

**Comment by aspramsh** [comment]
Okay @Burgyn. Thanks a lot.
