### ISSUE TITLE
Confusion in the interpretation of the routes

### ISSUE THREAD

**Issue by ilcos91** [Burgyn/MMLib.SwaggerForOcelot#65]
This is my configuration file:
`{
  "ReRoutes": [
    // AUTHENTICATION
    {
      "DownstreamPathTemplate": "/api/authentication",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 4001
        }
      ],
      "UpstreamPathTemplate": "/authentication",
      "UpstreamHttpMethod": [
        "Post" // Login
      ],
      // Login Service is not under Auth in order to be accessible
      "SwaggerKey": "Authentication"
    },
    {
      "DownstreamPathTemplate": "/api/authentication",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 4001
        }
      ],
      "UpstreamPathTemplate": "/authentication",
      "UpstreamHttpMethod": [
        "Get" // IsValidRequest
      ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "AxylogKey",
        "AllowedScopes": []
      },
      "SwaggerKey": "Authentication"
    },
    // AUTHENTICATION
    // ADMIN.ADMINUSER
    {
      "DownstreamPathTemplate": "/api/adminuser/{id}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/adminuser/{id}",
      "UpstreamHttpMethod": [ "Get" ],
      "SwaggerKey": "Admin"
    },
    // ADMIN.ADMINUSER
    // LOCALS.COMPANIES
    {
      "DownstreamPathTemplate": "/api/companies",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 6001
        }
      ],
      "UpstreamPathTemplate": "/companies",
      "UpstreamHttpMethod": [
        "Get"
      ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "AxylogKey",
        "AllowedScopes": []
      },
      "SwaggerKey": "Locals"
    },
    // LOCALS.COMPANIES
    // LOCALS.MASTERDATA
    {
      "DownstreamPathTemplate": "/api/masterdata",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 6001
        }
      ],
      "UpstreamPathTemplate": "/masterdata",
      "UpstreamHttpMethod": [
        "Get",
        "Post",
        "Put"
      ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "AxylogKey",
        "AllowedScopes": []
      },
      "SwaggerKey": "Locals"
    },
    {
      "DownstreamPathTemplate": "/api/masterdata/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 6001
        }
      ],
      "UpstreamPathTemplate": "/masterdata/{everything}",
      "UpstreamHttpMethod": [
        "Get",
        "Delete"
      ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "AxylogKey",
        "AllowedScopes": []
      },
      "SwaggerKey": "Locals"
    },
    // LOCALS.MASTERDATA
    // LOCALS.MASTERDATATYPE
    {
      "DownstreamPathTemplate": "/api/masterdatatype",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 6001
        }
      ],
      "UpstreamPathTemplate": "/masterdatatype",
      "UpstreamHttpMethod": [
        "Get",
        "Post",
        "Put"
      ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "AxylogKey",
        "AllowedScopes": []
      },
      "SwaggerKey": "Locals"
    },
    {
      "DownstreamPathTemplate": "/api/masterdatatype/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 6001
        }
      ],
      "UpstreamPathTemplate": "/masterdatatype/{everything}",
      "UpstreamHttpMethod": [
        "Get",
        "Delete"
      ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "AxylogKey",
        "AllowedScopes": []
      },
      "SwaggerKey": "Locals"
    },
    // LOCALS.MASTERDATATYPE
    // MIT SERVICE
    {
      "DownstreamPathTemplate": "/api/Vehicle",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 3001
        }
      ],
      "UpstreamPathTemplate": "/vehicle",
      "UpstreamHttpMethod": [
        "Post"
      ],
      "AuthenticationOptions": {
        "AuthenticationProviderKey": "AxylogKey",
        "AllowedScopes": []
      },
      "SwaggerKey": "MITService"
    }
    // MIT SERVICE
  ],
  "SwaggerEndPoints": [
    {
      "Key": "Authentication",
      "Config": [
        {
          "Name": "Authentication API",
          "Version": "v1",
          "Url": "https://localhost:4001/swagger/v1/swagger.json"
        }
      ]
    },
    {
      "Key": "Admin",
      "Config": [
        {
          "Name": "Admin API",
          "Version": "v1",
          "Url": "https://localhost:5001/swagger/v1/swagger.json"
        }
      ]
    },
    {
      "Key": "Locals",
      "Config": [
        {
          "Name": "Locals API",
          "Version": "v1",
          "Url": "https://localhost:6001/swagger/v1/swagger.json"
        }
      ]
    },
    {
      "Key": "MITService",
      "Config": [
        {
          "Name": "MIT Service API",
          "Version": "v1",
          "Url": "https://localhost:3001/swagger/v1/swagger.json"
        }
      ]
    }
  ],
  "GlobalConfiguration": {
    "RequestIdKey": "OcRequestId",
    "BaseUrl": "https://localhost:7000"
  }
}`

The route "/authentication" have to be separeted since the POST does not require authentication while the GET does.
When it generates the documentation it only reads the first one and for the authenticationController find only the POST service, the GET is ignored.
![image](https://user-images.githubusercontent.com/59659091/72362017-b7b06e00-36f2-11ea-94a7-7b4d6e35b07c.png)

Also for the "/masterdata" and "/masterdatatype" routes there are some problems. It seems like that when it looks for the masterdataController it also finds the masterdatatypeController and his services, then the routes for the "masterdatatype" are ignored like for the authenticationController.
![image](https://user-images.githubusercontent.com/59659091/72362972-4e315f00-36f4-11ea-9f96-011f4b7b36fc.png)
Then if I exchange the order of the "/masterdata" route with the "/masterdatatype" route it works in the right way and all the route are shown correctly.
![image](https://user-images.githubusercontent.com/59659091/72363066-77ea8600-36f4-11ea-8327-bef74189d35f.png)

I hope I've been clear enough, if needed I'll try to provide more explanation.

**Comment by Burgyn** [comment]
Hi,
thanks for your report. 
Please can you provide your downstream service `swagger.json`? It will help me investigate the problem.

Thanks

**Comment by ilcos91** [comment]
This is the swagger.json for the masterdataController and masterdatatypeController.
`{
  "openapi": "3.0.1",
  "info": {
    "title": "Locals API",
    "description": "Services collection to access local data of the ContextOwner",
    "version": "v1"
  },
  "paths": {
    "/api/Companies": {
      "get": {
        "tags": [
          "Companies"
        ],
        "summary": "Get the list of the enabled ContextOwner for the current Company",
        "parameters": [
          {
            "name": "Company",
            "in": "header",
            "description": "The ContextOwner",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "User",
            "in": "header",
            "description": "The user that sends the request",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Companies"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Companies"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Companies"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/MasterData/{code}": {
      "get": {
        "tags": [
          "MasterData"
        ],
        "summary": "Get the MasterData requested",
        "parameters": [
          {
            "name": "ContextOwner",
            "in": "header",
            "description": "The company to which the MasterData belongs, from header",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "code",
            "in": "path",
            "description": "The code of the MasterData to search for",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/MasterData"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MasterData"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/MasterData"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "MasterData"
        ],
        "summary": "Delete the MasterData with the specified parameters from the db",
        "parameters": [
          {
            "name": "ContextOwner",
            "in": "header",
            "description": "The company to which the MasterData belongs, from header",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "code",
            "in": "path",
            "description": "The code of the MasterData to delete",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/MasterData": {
      "get": {
        "tags": [
          "MasterData"
        ],
        "summary": "Get the MasterDatas of the requested type for the specified Company",
        "parameters": [
          {
            "name": "ContextOwner",
            "in": "header",
            "description": "The company to which the MasterDatas belong, from header",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "type",
            "in": "query",
            "description": "The type of the MasterDatas to search for, from query string",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/MasterData"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/MasterData"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/MasterData"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "MasterData"
        ],
        "summary": "Insert the MasterData object from the body into the db",
        "requestBody": {
          "description": "The MasterData object to insert, from body",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MasterData"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/MasterData"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/MasterData"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "put": {
        "tags": [
          "MasterData"
        ],
        "summary": "Update the db with the MasterData object specified",
        "requestBody": {
          "description": "The MasterData object to update, from body",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MasterData"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/MasterData"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/MasterData"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/MasterDataType": {
      "get": {
        "tags": [
          "MasterDataType"
        ],
        "summary": "Get all the MasterDataType from the current db",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/MasterDataType"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/MasterDataType"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/MasterDataType"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "MasterDataType"
        ],
        "summary": "Insert the MasterDataType object from the body into the db",
        "requestBody": {
          "description": "The MasterDataType object to insert, from body",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MasterDataType"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/MasterDataType"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/MasterDataType"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "put": {
        "tags": [
          "MasterDataType"
        ],
        "summary": "Update the db with the MasterDataType object specified",
        "requestBody": {
          "description": "The MasterData object to update, from body",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MasterDataType"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/MasterDataType"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/MasterDataType"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/MasterDataType/{id}": {
      "get": {
        "tags": [
          "MasterDataType"
        ],
        "summary": "Get the MasterDataType with the specified id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id to search for",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/MasterDataType"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MasterDataType"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/MasterDataType"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "MasterDataType"
        ],
        "summary": "Delete the MasterDataType with the specified id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the MasterDataTyper to delete",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Companies": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32"
          },
          "companyName": {
            "type": "string",
            "nullable": true
          },
          "owner": {
            "type": "string",
            "nullable": true
          },
          "administrator": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "type": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "MasterDataType": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "code": {
            "type": "integer",
            "format": "int32"
          }
        },
        "additionalProperties": false
      },
      "MasterData": {
        "type": "object",
        "properties": {
          "companyCode": {
            "type": "integer",
            "format": "int32"
          },
          "code": {
            "type": "integer",
            "format": "int32"
          },
          "type": {
            "type": "string",
            "nullable": true
          },
          "companyName": {
            "type": "string",
            "nullable": true
          },
          "typeId": {
            "type": "integer",
            "format": "int32"
          },
          "taCode": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "company": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Companies"
              }
            ],
            "nullable": true
          },
          "masterDataType": {
            "allOf": [
              {
                "$ref": "#/components/schemas/MasterDataType"
              }
            ],
            "nullable": true
          },
          "taCompany": {
            "allOf": [
              {
                "$ref": "#/components/schemas/Companies"
              }
            ],
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}`

**Comment by Burgyn** [comment]
Hi,

thank you for more information. It help me reproduce this behaviour.

It's bug. I'll try to fix it soon.

**Comment by Burgyn** [comment]
This issue is fixed in version `1.10.1`.

Thanks for cooperation.

**Comment by ilcos91** [comment]
Thank you for the prompt response.
