### ISSUE TITLE
SwaggerEndPoints configuration section is missing or empty for merged ocelot jsons

### ISSUE THREAD

**Issue by Cichyy7** [Burgyn/MMLib.SwaggerForOcelot#69]
Hi,

When I'm using per service ocelot.json configuration and file merging, I get **System.InvalidOperationException: "SwaggerEndPoints configuration section is missing or empty."**
Approach is described here: https://ocelot.readthedocs.io/en/latest/features/configuration.html#merging-configuration-files

When I put whole configuration in standalone ocelot.json, everything works fine. 

I would like to use both configurations merging and swagger on api gateway.

My configuration below:

**Startup.cs**
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOcelot();
            services.AddSwaggerForOcelot(Configuration);
            ...
        }
```
```
        public async void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
          ...
            app.UseStaticFiles();

            await app.UseSwaggerForOcelotUI(Configuration, opt =>
            {
                opt.PathToSwaggerGenerator = "/swagger/docs";

            }).UseOcelot();
           ...
        }
```
**Program.cs**
```
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.ConfigureAppConfiguration((hostingContext, config) =>
                    {
                        config
                            .AddOcelot("./Ocelot", hostingContext.HostingEnvironment)
                            .AddEnvironmentVariables();
                    });
                    webBuilder.UseStartup<Startup>();
                });
```

**ocelot.service1.json**
```
{
  "ReRoutes": [
    {
      "SwaggerKey": "service1",
      "UpstreamPathTemplate": "/service1/{everything}",
      "UpstreamHttpMethod": [ "GET", "PUT" ],
      "DownstreamPathTemplate": "/service1/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5010
        }
      ]
    }
  ]
}
```
**ocelot.global.json**
```
{
  "SwaggerEndPoints": [
    {
      "Key": "service1",
      "Config": [
        {
          "Name": "Service1 API V1",
          "Version": "v1",
          "Url": "http://localhost:5010/swagger/v1/swagger.json"
        }
      ]
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "http://localhost:5014"
  }
}
```

**Comment by Burgyn** [comment]
Hi,

thanks for your issue. I never test this scenario.

I'll look into it in the near future.

**Comment by Burgyn** [comment]
Hi,

when you use `.AddOcelot("./Ocelot", hostingContext.HostingEnvironment)` extension, then Ocelot merge configuration by own way and remove unknown elements.

As workaround you can move `SwaggerEndPoints` section into your `appsettings.json` file.
I hope, that help you.

**Comment by Cichyy7** [comment]
Hi,
Thanks for the quick reply!

Moving `SwaggerEndPoints` to `appsettings.json` of gateway indeed helped with `SwaggerEndPoints configuration section is missing or empty`
 but now i'm getting 
`IndexOutOfRangeException: Index was outside the bounds of the array.`
`MMLib.SwaggerForOcelot.Middleware.SwaggerForOcelotMiddleware.GetEndPointInfo(string path)`

Also, I'm wondering how to move `"SwaggerKey": "service1"` from ReRoutes of service. From what I saw `.AddOcelot()` is also removing it from merged `ocelot.json`.

**Comment by Burgyn** [comment]
Hi,

yes you are right `SwaggerKey` is removed. Unfortunately now I don't have any workaround for this. I apologize.

**Comment by Cichyy7** [comment]
Hi,

No problem ;)
Thanks for the help anyway ;)

**Comment by Navaladi2019** [comment]
Hi,
 On such case if we can take ServiceName from route and map it to SwaggerKey.it will work

**Comment by habtu12** [comment]
You can config teh Program.cs to read ocelot.json or ocelot.dev.json like this:

**Comment by MostafaAhm** [comment]
> Hi,
> 
> When I'm using per service ocelot.json configuration and file merging, I get **System.InvalidOperationException: "SwaggerEndPoints configuration section is missing or empty."** Approach is described here: https://ocelot.readthedocs.io/en/latest/features/configuration.html#merging-configuration-files
> 
> When I put whole configuration in standalone ocelot.json, everything works fine.
> 
> I would like to use both configurations merging and swagger on api gateway.
> 
> My configuration below:
> 
> **Startup.cs**
> 
> ```
>         public void ConfigureServices(IServiceCollection services)
>         {
>             services.AddOcelot();
>             services.AddSwaggerForOcelot(Configuration);
>             ...
>         }
> ```
> 
> ```
>         public async void Configure(IApplicationBuilder app, IWebHostEnvironment env)
>         {
>           ...
>             app.UseStaticFiles();
> 
>             await app.UseSwaggerForOcelotUI(Configuration, opt =>
>             {
>                 opt.PathToSwaggerGenerator = "/swagger/docs";
> 
>             }).UseOcelot();
>            ...
>         }
> ```
> 
> **Program.cs**
> 
> ```
>         public static IHostBuilder CreateHostBuilder(string[] args) =>
>             Host.CreateDefaultBuilder(args)
>                 .ConfigureWebHostDefaults(webBuilder =>
>                 {
>                     webBuilder.ConfigureAppConfiguration((hostingContext, config) =>
>                     {
>                         config
>                             .AddOcelot("./Ocelot", hostingContext.HostingEnvironment)
>                             .AddEnvironmentVariables();
>                     });
>                     webBuilder.UseStartup<Startup>();
>                 });
> ```
> 
> **ocelot.service1.json**
> 
> ```
> {
>   "ReRoutes": [
>     {
>       "SwaggerKey": "service1",
>       "UpstreamPathTemplate": "/service1/{everything}",
>       "UpstreamHttpMethod": [ "GET", "PUT" ],
>       "DownstreamPathTemplate": "/service1/{everything}",
>       "DownstreamScheme": "http",
>       "DownstreamHostAndPorts": [
>         {
>           "Host": "localhost",
>           "Port": 5010
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> **ocelot.global.json**
> 
> ```
> {
>   "SwaggerEndPoints": [
>     {
>       "Key": "service1",
>       "Config": [
>         {
>           "Name": "Service1 API V1",
>           "Version": "v1",
>           "Url": "http://localhost:5010/swagger/v1/swagger.json"
>         }
>       ]
>     }
>   ],
>   "GlobalConfiguration": {
>     "BaseUrl": "http://localhost:5014"
>   }
> }
> ```

Hi,
sorry for the 3 years delay,
i was making a gateway 2 weeks ago with ocelot and MMLib.SwaggerForOcelot and i have faced the same problem when using ocelot merging the swagger properties and swagger endpoints are missing then i read the ocelot implementation

![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/abc9c796-a6f3-4fa3-8139-ca3b35ce44a7)

![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/23891f7a-ce29-4954-9867-68a25bd599ce)

 and i found that they are using specific properties so i have added more my self 
![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/11929af5-beb9-43bb-8837-e04e5b4ddfa6)
![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/2d73429d-3c4b-4748-959c-1ec4331bf704)
![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/80536009-1596-44a1-b9c8-8cd53ec114b7)
in the last image the FileRoute is the for ocelot i just have inherited from it,
and for the implementation with the help of this awesome guy i got the idea from him to add my own swagger end point  [the link](https://stackoverflow.com/a/69429368/12448674)

so as ocelot said in the documentation they use the ocelot.json as the entry point so we made our own extension and put all the files content in the ocelot.json with our extra properties  as you can see in the previous images 
and for the extension implementation
![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/7afb9e16-cc97-42f3-bd43-8ccba9daf641)


`public static class ConfigurationBuilderExtensions
{
    public static IConfigurationBuilder AddOcelotConfigFiles(this IConfigurationBuilder builder, string folder, string[] appNames, IWebHostEnvironment env)
    {
        const string primaryConfigFile = "ocelot.json";

        var files = new DirectoryInfo(folder)
            .EnumerateFiles()
            .Where(fi => fi.Name.Contains($"ocelot.{env.EnvironmentName}.json") && appNames.Any(e => fi.Name.Contains(e)))
            .ToList();

        var fileConfiguration = new MyFileConfiguration();

        foreach (var file in files)
        {
            if (files.Count > 1 && file.Name.Equals(primaryConfigFile, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var lines = File.ReadAllText(file.FullName);

            var config = JsonConvert.DeserializeObject<MyFileConfiguration>(lines);

            fileConfiguration.Aggregates.AddRange(config.Aggregates);
            fileConfiguration.Routes.AddRange(config.Routes);
            fileConfiguration.SwaggerEndPoints.AddRange(config.SwaggerEndPoints);
        }

        var json = JsonConvert.SerializeObject(fileConfiguration);

        File.WriteAllText(primaryConfigFile, json);

        builder.AddJsonFile(primaryConfigFile, true, true);

        return builder;
    }
}` 

and for the programs.cs
![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/7e091eee-9809-448b-ad3c-33d9a0d2e096)

and that's it.

**Comment by MostafaAhm** [comment]
Hi,
sorry for the 3 years delay,
i was making a gateway 2 weeks ago with ocelot and MMLib.SwaggerForOcelot and i have faced the same problem when using ocelot merging the swagger properties and swagger endpoints are missing then i read the ocelot implementation

![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/abc9c796-a6f3-4fa3-8139-ca3b35ce44a7)

![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/23891f7a-ce29-4954-9867-68a25bd599ce)

 and i found that they are using specific properties so i have added more my self 
![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/11929af5-beb9-43bb-8837-e04e5b4ddfa6)
![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/2d73429d-3c4b-4748-959c-1ec4331bf704)
![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/80536009-1596-44a1-b9c8-8cd53ec114b7)
in the last image the FileRoute is the for ocelot i have just inherited from it,
and for the implementation with the help of this awesome guy i got the idea from him to add my own swagger end point  [the link](https://stackoverflow.com/a/69429368/12448674)

so as ocelot said in the documentation they use the ocelot.json as the entry point so we made our own extension and put all the files content in the ocelot.json with our extra properties  as you can see in the previous images 
and for the extension implementation
![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/7afb9e16-cc97-42f3-bd43-8ccba9daf641)


`public static class ConfigurationBuilderExtensions
{
    public static IConfigurationBuilder AddOcelotConfigFiles(this IConfigurationBuilder builder, string folder, string[] appNames, IWebHostEnvironment env)
    {
        const string primaryConfigFile = "ocelot.json";

        var files = new DirectoryInfo(folder)
            .EnumerateFiles()
            .Where(fi => fi.Name.Contains($"ocelot.{env.EnvironmentName}.json") && appNames.Any(e => fi.Name.Contains(e)))
            .ToList();

        var fileConfiguration = new MyFileConfiguration();

        foreach (var file in files)
        {
            if (files.Count > 1 && file.Name.Equals(primaryConfigFile, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var lines = File.ReadAllText(file.FullName);

            var config = JsonConvert.DeserializeObject<MyFileConfiguration>(lines);

            fileConfiguration.Aggregates.AddRange(config.Aggregates);
            fileConfiguration.Routes.AddRange(config.Routes);
            fileConfiguration.SwaggerEndPoints.AddRange(config.SwaggerEndPoints);
        }

        var json = JsonConvert.SerializeObject(fileConfiguration);

        File.WriteAllText(primaryConfigFile, json);

        builder.AddJsonFile(primaryConfigFile, true, true);

        return builder;
    }
}` 

and for the programs.cs
![image](https://github.com/Burgyn/MMLib.SwaggerForOcelot/assets/56700910/7e091eee-9809-448b-ad3c-33d9a0d2e096)
