### ISSUE TITLE
After updating swashbuckle to version 5.0.0, some models have trouble serializing

### ISSUE THREAD

**Issue by slashersvk** [Burgyn/MMLib.SwaggerForOcelot#70]
**Description**
Using .net core 3.0 project, after updating swashbuckle library to version 5.0.0 some models have trouble serializing and swagger renders an error message upon clicking some routes.
In my case the error had problems with Enum and some classes.

**Expected behavior**
Models should be serialized.

**To Reproduce**
1. Open swagger
2. Click on route

**Comment by aspramsh** [comment]
I have the same problem, here are my errors:
![image](https://user-images.githubusercontent.com/26508162/72981470-43fb1900-3df6-11ea-99ef-2790822a8fab.png)

**Comment by Burgyn** [comment]
Fixed in version `1.10.3`.

**Comment by aspramsh** [comment]
Thank you.
