### ISSUE TITLE
Resolver error at ... Could not resolve reference: Could not resolve pointer: ...

### ISSUE THREAD

**Issue by ilcos91** [Burgyn/MMLib.SwaggerForOcelot#73]
Hi,
I'm having two different behaviour in the swagger of my end point and in SwaggerForOcelot of my gateway.
I have defined an object that is also a property of another object that I defined.
In the swagger of the end point everything works fine, I can navigate all the properties.
![image](https://user-images.githubusercontent.com/59659091/73438782-e2cfca00-434e-11ea-8800-0feb3318a318.png)
While when I try to navigate this objects and properties in the page of the gateway, I get this error:
![image](https://user-images.githubusercontent.com/59659091/73438952-2c201980-434f-11ea-93e3-221c81178c3f.png)
I'm working with the 1.10.1 version.

I'll be happy the give any further information if needed.

Any help is welcome,
Thank you in advance!

**Comment by Burgyn** [comment]
Hi,

please try version `1.10.3`. It's look like problem resolved in PR #71

**Comment by ilcos91** [comment]
Yes, I had an outdated version, not it works.
Thank you and sorry for the waste of time

**Comment by Burgyn** [comment]
It's OK. I'm glad it's solved.

**Comment by jimmy-vo-librestream** [comment]
I am on dotnet core 3.1. I had this problem in `2.5.1`. I upgraded MMLib.SwaggerForOcelot to `3.2.1` but it doesn't help.
Upgrading dotnet core to 5.0 is not an option for me. Is there any work around?
