### ISSUE TITLE
hi i'm new to Ocelot and .net core

### ISSUE THREAD

**Issue by Raj1633** [Burgyn/MMLib.SwaggerForOcelot#74]
hi i am new to Ocelot and .net core , when i browse for some example i found your github project ,  can some one help me on how to run this project and explore more, whether each project has to be hosted prior accessing it or can i run in visual studio as multiple project run at time ? which one is the start up project here to begin and Test

**Comment by Burgyn** [comment]
Hi,

I'm not sure what you want study. Ocelot? If yes try [Ocelot documentaion](https://ocelot.readthedocs.io/en/latest/).
This repo is "only" integration library w bring together Ocelot and Swagger.

Anyway,
if you want explore demo projects in this repo follow nex steps.

1. Set multiples project starup in your Visual Studio. 
Multiple startup projects:
- ApiGateway (this is Ocelot api gateway)
- ContactService (microservice)
- OrderService (microservice)
- PetstoreService (microservice)
- ProcetService (microservice)

2. Run projects _CTRL + F5_
3. Show `http://localhost:{apiGatewayPort}/swagger` in your browser.

**Comment by Raj1633** [comment]
@Burgyn  thanks for  your response , i'm trying to understanding integration of ocelot to my swagger microservices , could you please give some more information on the  ocelot and .net core version, i'm running this solution in Visual studio 2019, experiencing some issue ,

**Comment by Raj1633** [comment]
@Burgyn  some how i manged to run the application with your help , but the ports keep on changing couldn't guess so thinking to host this individual app , i've  knowledge on host asp.net  application but i'm new to host Asp.net Core application , can some one throw some light on this  please, i'm eager to learn this ocelot:)

**Comment by Burgyn** [comment]
Hi,

the microservices in this demo (`Project`, `Contact`, `PetStore`, `Order`) set the launch URL in the `Main` method in the `Program.cs` by `.UseUrls` methods.

ApiGateway project does not have specific launch URL. I recommand you study [`launchSettings.json` profile.]( https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1)
