### ISSUE TITLE
File Merge Support

### ISSUE THREAD

**Issue by amadard** [Burgyn/MMLib.SwaggerForOcelot#79]
I have the same problem as #69 and built my own fix by making my own version of the file merge code.

@Burgyn  How would you like me to proceed to get you the code to review to decide if you want to take my changes?

**Comment by Burgyn** [comment]
Hi, thanks for your investigation and effort.

Standard procedure is:

Fork this repo
Create new branche
Make your changes
Write UnitTest.
If it's new feature write info into documentation (readme.md file)
Commit / push
Create pull request
