### ISSUE TITLE
Swagger not working with self signed certificate.

### ISSUE THREAD

**Issue by mateo19851** [Burgyn/MMLib.SwaggerForOcelot#82]
**Describe the bug**
I have a service with swagger with self signed certificate. There is no possibility to configure request to use self signed certificates.

**Expected behavior**
There should be an option to set self signed certificates as valid.

**To Reproduce**
The service with selfsigned certificate is required.

**Comment by Burgyn** [comment]
Hi,

thanks for your report. 

Currently I do not plan to implement it.
But, contributing is open ;-)
