### ISSUE TITLE
Unable to integrate swagger with Gateway

### ISSUE THREAD

**Issue by sandyrepo** [Burgyn/MMLib.SwaggerForOcelot#84]
**Describe the bug**
I have ocelot with consul service discovery, whenever swagger is fetching from api gateway it returns empty path and contents and no services found but
without gateway swagger is displaying the services
**Expected behavior**
with localhost url its working but with service discovery its not working 

**To Reproduce**
If it is a possible attache:
1. Original downstream `swagger.json`.
2. Ocelot ReRoutes configuration.

**Comment by sandyrepo** [comment]
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/{url}",
      "DownstreamScheme": "http",
      "UpstreamPathTemplate": "/abc/{url}",
      "UpstreamHttpMethod": [ "Get", "POST", "PUT" ],
      "ServiceName": "ani.abc.api",
      "LoadBalancerOptions": {
        "Type": "LeastConnection"
      },
      "RateLimitOptions": {
        "ClientWhitelist": [],
        "EnableRateLimiting": true,
        "Period": "1s",
        "PeriodTimespan": 1,
        "Limit": 1
      },
      "SwaggerKey": "swaggerabc"
    }
  ],
  "SwaggerEndPoints": [
    {
      "Key": "swaggerabc",
      "Config": [
        {
          "Name": "abc API",
          "Version": "v1",
          "Url": "http://ani.abc.api:80/swagger/v1/swagger.json"
        }
      ]
    }
  ],
  "GlobalConfiguration": {
    "ServiceDiscoveryProvider": {
      "Host": "consul",
      "Port": 8500,
      "Type": "Consul"
    },
    "RequestIdKey": "OcRequestId"
  }
}




--------------Gateway startup file--------------
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddOcelot().AddConsul();
            services.AddSwaggerForOcelot(Configuration);
            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

           // app.UseHttpsRedirection();

            app.UseRouting();

            //app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
            //app.UseSwaggerForOcelotUI(Configuration).UseOcelot().Wait();
            app.UseSwaggerForOcelotUI(Configuration, opt =>
            {
                opt.ReConfigureUpstreamSwaggerJson = AlterUpstreamSwaggerJson;               
            }).UseOcelot().Wait();

            //app.UseSwaggerForOcelotUI(Configuration, opt =>
            //{
            //    opt.PathToSwaggerGenerator = "/swagger/docs";
            //});
            //app.UseSwaggerForOcelotUI(Configuration, opt =>
            //{
            //    opt.ReConfigureUpstreamSwaggerJson = AlterUpstreamSwaggerJson;
            //    //opt.DownstreamSwaggerEndPointBasePath = "/swagger/docs";
            //    //opt.PathToSwaggerGenerator = "/swagger/docs";
            //}).UseOcelot().Wait();

        }
        public string AlterUpstreamSwaggerJson(HttpContext context, string swaggerJson)
        {
            var swagger = JObject.Parse(swaggerJson);            
            return swagger.ToString(Formatting.Indented);
        }
-------------------------------------
-------------------------------------Microservice startup file

public void ConfigureServices(IServiceCollection services)
        {
           
            services.AddControllers();
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "abc API", Version = "v1" });
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");                
            });
        }

**Comment by Pavan1foru** [comment]
I tried with setting swaggerkey as service name but got http error "cannot assign address"

**Comment by Burgyn** [comment]
Hi @sandyrepo 

thanks for your report. It's look like problem with transformation by Ocelot config. You use `{url}` as wild card in your configuration. Unfortunately now this project support only `{everything}` as wildcard. (see #68) 

Please try use `{everything}`.

**Comment by sandyrepo** [comment]
Thanks for your quick reply. this resolved my issue
