### ISSUE TITLE
VirtualDirectory not reflects on swagger ui

### ISSUE THREAD

**Issue by karabiberoglu** [Burgyn/MMLib.SwaggerForOcelot#85]
Hi,

in my configuration, I set the virtual directory. 
when I check my rest methods on swagger ui, virtual directory is missing and when i try to execute the methods, I get 404 error.

but when i manually add virtual host to request url. it works.
are there any workaround to handle this issue?

Thanks,

**Comment by Burgyn** [comment]
Hi,
thanks for your report.

Please, can you provide your `ocelot.json` configuration? And example of downstream `swagger.json`?

thanks.

**Comment by karabiberoglu** [comment]
Thanks for your response, files are as following.

[ocelot.json.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/4570524/ocelot.json.txt)
[v1.json.txt](https://github.com/Burgyn/MMLib.SwaggerForOcelot/files/4570525/v1.json.txt)

**Comment by Burgyn** [comment]
Hi,

I'm not sure, but it's look like you have wrong configuration.

Your downstream path looks like this `/MyWebApi/api/{everything}`, so I suppouse that `MyWebApi` is name of your virtual directory in IIS. But to property `VirtualDirectory` you setting `/MyApiGateway`, why not `/MyWebApi`?

**Comment by djesusnet** [comment]
Hello guys,

I'm having trouble running Swagger from my gateway api.
![image](https://user-images.githubusercontent.com/50085026/96051908-e068be00-0e52-11eb-93c2-c5ebeebb1893.png)

As we saw the image when executing get, a 404 error occurs and when I go to the api other than the gateway, it works correctly. Do you know what it can be?

**Comment by Burgyn** [comment]
Hi @djesusnet 

You use Ocelot with version `16.0.1.` [which have breaking change](https://github.com/ThreeMammals/Ocelot/releases/tag/16.0.0), that rename `ReRoutes` -> `Routes` and you still using `ReRoutes` in your configuration.

Try rename `ReRoutes` to `Routes` and remove property `TransformByOcelotConfig` from `SwaggerEndPoints`.
