### ISSUE TITLE
Getting issue in .Net core 3.1

### ISSUE THREAD

**Issue by BHARAT703** [Burgyn/MMLib.SwaggerForOcelot#86]
**Describe the bug**
Getting this error with simple micro service structure that uses Ocelot. see attached snap.

`An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.`

![image](https://user-images.githubusercontent.com/24493137/79877293-b1c0dc00-8409-11ea-95b5-6a325a8368f5.png)

**To Reproduce**
Here I have attached my Ocelot configuration file. 

![image](https://user-images.githubusercontent.com/24493137/79877407-d2893180-8409-11ea-976c-5a6f5a9ce03e.png)

My start up class.
![image](https://user-images.githubusercontent.com/24493137/79878027-90acbb00-840a-11ea-90e3-f5b9f82e1eb7.png)

I am trying to resolve this issue from last 2 days, but it's just not working so adding this here to get some help. Thanks.

**Comment by Burgyn** [comment]
Hi,

it's look like you use [Service Discovery](https://github.com/Burgyn/MMLib.SwaggerForOcelot#service-discovery) configuration. In your case (if don't use Service Discovery, like Service Fabric, Kubernetes, ...) you have to use standard swagger endpoint configuration, like:

```json
"Key": "price",
"Config": [
   {
      "Name": "Price API",
      "Version": "v1",
      "Url": "http://localhost:5100/swagger/v1/swagger.json"
    }
 ]
```
