### ISSUE TITLE
How to log request json body in case of error in ocelot

### ISSUE THREAD

**Issue by rajeshgithub001** [Burgyn/MMLib.SwaggerForOcelot#91]
I am serilog to log error from ocelot in case of downstream giving any error.
Using serilog i am sending the exception details to Application Insight.

Serilog configuration:-

"Serilog": {
"Using": [ "Serilog.Sinks.ApplicationInsights" ],
"MinimumLevel": {
"Default": "Information",
"Override": {
"Microsoft": "Warning"
}
},
"WriteTo": [
{
"Name": "ApplicationInsights",
"Args": {
"instrumentationKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
}
}
],
"Enrich": [ "FromLogContext" ],
"Properties": {
"Application": "API GATEWAY"
}
}

Now i want to log request json body in case of error only , How will i do it ?

Middleware didn't work as it didn't catch any ocelot exception, so its out of question.

**Comment by Burgyn** [comment]
Hi,

sorry, but by your description it looks like issue to [Ocelot repo](https://github.com/ThreeMammals/Ocelot).
