### ISSUE TITLE
Schema Invalid : http port not valid

### ISSUE THREAD

**Issue by ThiyagarajanVellaichamy** [Burgyn/MMLib.SwaggerForOcelot#93]
everything has been rendered in view, when trying to execute API through Swagger, getting invalid schema. find the configuration and screen shot below, please help me out, if there I missed anything from my end.

ocelot.json:
{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/auth-service/{everything}",
      "UpstreamHttpMethod": [ "Get", "Post" ],
      "SwaggerKey": "authswagger",
      "VirtualDirectory": "/authswagger"
    }
  ],
  "SwaggerEndPoints": [
    {
      "Key": "gateway",
      "TransformByOcelotConfig": false,
      "Config": [
        {
          "Name": "Gateway",
          "Version": "v1",
          "Url": "https://localhost:5003/swagger/v1/swagger.json"
        }
      ]
    },
    {
      "Key": "authswagger",
      "Config": [
        {
          "Name": "Authentication API",
          "Version": "v1",
          "Url": "https://localhost:5001/api/swagger/v1/swagger.json"
        }
      ]
    }
  ],
  "GlobalConfiguration": {
    "BaseUrl": "https://localhost"
  }
 }
![Screenshot 2020-05-03 at 23 12 28](https://user-images.githubusercontent.com/63137672/80921372-9ce23200-8d93-11ea-8827-4623befeb811.png)

**Comment by Burgyn** [comment]
Hi,
I try to figure out where the problem is, but without success.

I don't know why he create the wrong address. `localhost://5003`. You do not have a special value filled in baseUrl in downstream service swagger?

**Comment by ThiyagarajanVellaichamy** [comment]
> Hi,
> I try to figure out where the problem is, but without success.
> 
> I don't know why he create the wrong address. `localhost://5003`. You do not have a special value filled in baseUrl in downstream service swagger?
> 
> And one question? Need you really `VirtualDirectory`? `VirtualDirectory` is necessary only if you host your service as virtual app in IIS.

Thanks for the valuable Answer,

I have removed virtual directory too, but it gives same result.

1. I have used API Gate way which is running under 5003 port.
2. It has ocelot configuration, and ran the application then navigated to swagger page.
3. It has two option
      I. Gate Way API - port: 5003
      ii. Authentication API -port: 5001
4. when I'm choosing Authentication API, it's rendered with API in swagger page, but url comes  like localhost://5003, Is there anyway to get resolved or Am I done anything wrong in the configuration.

Kindly help me out.

**Comment by Burgyn** [comment]
For further investigation, Can you provide your AuthorizationApi downstream swagger (original, before transforming by this library).

Thanks.

**Comment by ThiyagarajanVellaichamy** [comment]
> For further investigation, Can you provide your AuthorizationApi downstream swagger (original, before transforming by this library).
> 
> Thanks.
 services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "Authentication Services", Version = "v1", Description = "Authentication service" });
                c.AddSecurityDefinition("Bearer",
                   new OpenApiSecurityScheme
                   {
                       In = ParameterLocation.Header,
                       Description = "Please enter into field the word 'Bearer' following by space and JWT",
                       Name = "Authorization",
                       Type = SecuritySchemeType.ApiKey,
                       Scheme = "Bearer"
                   });
                c.AddSecurityRequirement(new OpenApiSecurityRequirement()
                {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference
                            {
                                Type = ReferenceType.SecurityScheme,
                                Id = "Bearer"
                            },
                            Scheme = "oauth2",
                            Name = "Bearer",
                            In = ParameterLocation.Header
                        },
                        new List<string>()
                    }
                });
            });

**Comment by Burgyn** [comment]
sorry but i meant swagger.json.

**Comment by Burgyn** [comment]
Hi,

thanks for sharing your settings, they helped me understand the issue.

## Problem description

You have (I don't know why) in your swagger this setting:

```json
"servers": [
  {
    "url": "/api"
  }
]
```
See [swagger documentation](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#modify-swagger-with-request-context)

## Workaround

If you really need this settings, than you can change it in ocelot config.

```json
{
  "Key": "authswagger",
  "HostOverride": "",
  "Config": [
    {
      "Name": "Authentication API",
      "Version": "v1",
      "Url": "http://localhost:5300/swagger.json"
    }
  ]
}
```

The key is `"HostOverride": "",`

I hope I helped.

**Comment by ThiyagarajanVellaichamy** [comment]
> Hi,
> 
> thanks for sharing your settings, they helped me understand the issue.
> 
> ## Problem description
> You have (I don't know why) in your swagger this setting:
> 
> ```json
> "servers": [
>   {
>     "url": "/api"
>   }
> ]
> ```
> 
> See [swagger documentation](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#modify-swagger-with-request-context)
> 
> ## Workaround
> If you really need this settings, than you can change it in ocelot config.
> 
> ```json
> {
>   "Key": "authswagger",
>   "HostOverride": "",
>   "Config": [
>     {
>       "Name": "Authentication API",
>       "Version": "v1",
>       "Url": "http://localhost:5300/swagger.json"
>     }
>   ]
> }
> ```
> 
> The key is `"HostOverride": "",`
> 
> I hope I helped.

Yes, You resolved the issue, thanks.

**Comment by Burgyn** [comment]
I am glad to hear that
