### ISSUE TITLE
When will the dynamic routing of consul be possible?

### ISSUE THREAD

**Issue by gudufy** [Burgyn/MMLib.SwaggerForOcelot#95]
When will the dynamic routing of consul be possible?

**Comment by Burgyn** [comment]
Hi,

This library generally uses Service Discovery from Ocelot. Unfortunetly I never tested scenario with the Consul, because I have no experience with this service.

#94 is similar issue. If you have any other info that could help solve this I will be happy if you provide.

**Comment by gudufy** [comment]
I implemented an IConfigurationBuilder extension, When Ocelot uses Consul, it can generate ocelot.json based on the list of services returned by Consul:
`using Consul;
using Microsoft.Extensions.Configuration;
using MMLib.SwaggerForOcelot.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SpaGateway
{
    /// <summary>
    /// 自动生成ocelot及swagger配置文件
    /// </summary>
    public static class OcelotConfigExtensions
    {
        public static IConfigurationBuilder AddOcelotAndSwaggerJson(this IConfigurationBuilder builder,string contentRootPath)
        {
            var config = builder.Build();
            var consulClient = new ConsulClient(c => c.Address = new Uri($"{config["ConsulAddress"]}"));
            var services = Task.Run(async () => {
                return await consulClient.Agent.Services();
            }).Result;

            if (services == null || !services.Response.Any())
                return builder;

            var endPointOptions = new List<SwaggerEndPointOptions>();
            var reRoutes = new List<OcelotReRouteOption>();
            foreach (var (key, value) in services.Response)
            {
                endPointOptions.Add(new SwaggerEndPointOptions
                {
                    Key = value.Service,
                    Config = new List<SwaggerEndPointConfig> {
                            new SwaggerEndPointConfig{
                                 Name = $"{value.Service} api",
                                 Url=$"http://{value.Address}:{value.Port}/swagger/v1/swagger.json",
                                 Version="v1"
                            }
                        }
                });

                reRoutes.Add(new OcelotReRouteOption
                {
                    DownstreamHostAndPorts = new List<DownstreamHostAndPort> {
                        new DownstreamHostAndPort{ Host = value.Address, Port = value.Port }
                     },
                    DownstreamPathTemplate = "/api/{everything}",
                    DownstreamScheme = "http",
                    SwaggerKey = value.Service,
                    UpstreamPathTemplate = $"/api/{value.Service}/{{everything}}"
                });
            }

            using (StreamWriter file = File.CreateText(Path.Combine(contentRootPath, "ocelot.json")))
            {
                JsonSerializer serializer = new JsonSerializer();
                serializer.Formatting = Formatting.Indented;
                serializer.Serialize(file, new OcelotConfig
                {
                    ReRoutes = reRoutes,
                    SwaggerEndPoints = endPointOptions,
                    GlobalConfiguration = new GlobalConfiguration
                    {
                        BaseUrl = null
                    }
                });
            }

            builder.AddJsonFile("ocelot.json", false, true);

            return builder;
        }
    }

    public class OcelotConfig
    {
        public GlobalConfiguration GlobalConfiguration { get; set; }
        public List<OcelotReRouteOption> ReRoutes { get; set; }
        public List<SwaggerEndPointOptions> SwaggerEndPoints { get; set; }
    }

    public class GlobalConfiguration
    {
        public string BaseUrl { get; set; }
    }

    public class OcelotReRouteOption
    {
        public string DownstreamPathTemplate { get; set; }
        public string DownstreamScheme { get; set; }
        public List<DownstreamHostAndPort> DownstreamHostAndPorts { get; set; }
        public string UpstreamPathTemplate { get; set; }
        public string SwaggerKey { get; set; }
    }

    public class DownstreamHostAndPort
    {
        public string Host { get; set; }
        public int Port { get; set; }
    }
}
`
1. Program.cs
`using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

namespace SpaGateway
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                 .ConfigureAppConfiguration((hostingContext, config) =>
                 {
                     config
                         .AddOcelotAndSwaggerJson(hostingContext.HostingEnvironment.ContentRootPath)
                         .AddEnvironmentVariables();
                 })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}`

2. appsettings.json add key
"ConsulAddress": "http://127.0.0.1:8500",

3. The resulting file
`{
  "GlobalConfiguration": {
    "BaseUrl": null
  },
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5001
        }
      ],
      "UpstreamPathTemplate": "/api/basedata/{everything}",
      "SwaggerKey": "basedata"
    },
    {
      "DownstreamPathTemplate": "/api/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 5050
        }
      ],
      "UpstreamPathTemplate": "/api/identity/{everything}",
      "SwaggerKey": "identity"
    }
  ],
  "SwaggerEndPoints": [
    {
      "Key": "basedata",
      "VersionPlaceholder": "{version}",
      "KeyToPath": "basedata",
      "Config": [
        {
          "Name": "basedata api",
          "Version": "v1",
          "Url": "http://localhost:5001/swagger/v1/swagger.json"
        }
      ],
      "HostOverride": null
    },
    {
      "Key": "identity",
      "VersionPlaceholder": "{version}",
      "KeyToPath": "identity",
      "Config": [
        {
          "Name": "identity api",
          "Version": "v1",
          "Url": "http://localhost:5050/swagger/v1/swagger.json"
        }
      ],
      "HostOverride": null
    }
  ]
}`
