### ISSUE TITLE
Error routing endpoints

### ISSUE THREAD

**Issue by dadjh85** [Burgyn/MMLib.SwaggerForOcelot#96]
I have a problem in the configuration of this nuget, I have a configuration file like the one below:
`{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/samm/apitaer/{everything}",
      "DownstreamScheme": "http",
      "DownstreamHostAndPorts": [
        {
          "Host": "MYIPSERVER",
          "Port": 8080
        }
      ],
      "UpstreamPathTemplate": "/api/request/{everything}",
      "DangerousAcceptAnyServerCertificateValidator": true,
      "SwaggerKey": "request"
    }
  ],
  "SwaggerEndPoints": [
    {
      "Key": "request",
      "Config": [
        {
          "Name": "Taer API",
          "Version": "v1",
          "Url": "http://MYIPSERVER:8080/samm/apitaer/swagger/v1/swagger.json"
        }
      ]
    }
  ]
}`

and that loads my microservice routes without any problem, but when I run an endpoint it produces the following problem:

**TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from MYIP://8080/api/req/status**

the route is not loaded correctly, but if I call the route that should be called by postman it doesn't produce any problem.

locally with this configuration does work for me:

`{
  "ReRoutes": [
    {
      "DownstreamPathTemplate": "/{everything}",
      "DownstreamScheme": "https",
      "DownstreamHostAndPorts": [
        {
          "Host": "localhost",
          "Port": 44320
        }
      ],
      "UpstreamPathTemplate": "/api/request/{everything}",
      "DangerousAcceptAnyServerCertificateValidator": true,
      "SwaggerKey": "request"
    }
  ],
  "SwaggerEndPoints": [
    {
      "Key": "request",
      "Config": [
        {
          "Name": "Taer API",
          "Version": "v1",
          "Url": "https://localhost:44320/swagger/v1/swagger.json"
        }
      ]
    }
  ]
}`

I don't understand why he builds the routes wrong when I run an endpoint.

**Comment by dadjh85** [comment]
I have added a pull request with the solution to this problem, could you check it to see if it could be included in a new version of the nuget? Thank you very much.

**Comment by Burgyn** [comment]
Hi,

your changes are available in [`v2.0.0-alpha.4`](https://www.nuget.org/packages/MMLib.SwaggerForOcelot/2.0.0-alpha.4)

Thanks for cooperation.
