### ISSUE TITLE
Wrong schema & Hostname when using "Try it out" in Swagger UI

### ISSUE THREAD

**Issue by TheJoeIaut** [Burgyn/MMLib.SwaggerForOcelot#98]
I have a gateway and one Identity API running in Docker Container. When trying to execute a Method via "Try it out" the URL of the Identity Service is wrong. Somehow localhost is used as schema and the port as hostname.

I Access the Gateway Swagger UI via http://localhost:15000/swagger/index.html:

![image](https://user-images.githubusercontent.com/8371896/82335541-c765f900-99e9-11ea-923e-03d6fe3ead9f.png)

The incorrect request:

![image](https://user-images.githubusercontent.com/8371896/82335616-e3699a80-99e9-11ea-89bb-bbafc294e875.png)

Downstream Config:

![image](https://user-images.githubusercontent.com/8371896/82335785-1744c000-99ea-11ea-90bc-44d5ba64e28b.png)

Swagger Endpoint:

![image](https://user-images.githubusercontent.com/8371896/82335925-3e02f680-99ea-11ea-9392-8562e526249c.png)

Downstream swagger.json (retrieved via localhost:17000 since I have no access to http://identityapi/swagger/v1/swagger.json)

{
  "x-generator": "NSwag v13.5.0.0 (NJsonSchema v10.1.15.0 (Newtonsoft.Json v12.0.0.0))",
  "openapi": "3.0.0",
  "info": {
    "title": "Identity API",
    "description": "Create API Keys with various roles",
    "version": "v1"
  },
  "servers": [
    {
      "url": "http://localhost:17000"
    }
  ],
  "paths": {
    "/api/ApiKey": {
      "get": {
        "tags": [
          "ApiKey"
        ],
        "operationId": "ApiKey_GetApiKey",
        "parameters": [
          {
            "name": "client",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          },
          {
            "name": "roles",
            "in": "query",
            "style": "form",
            "explode": true,
            "schema": {
              "type": "array",
              "nullable": true,
              "items": {
                "type": "string"
              }
            },
            "x-position": 2
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "API Key": {
        "type": "apiKey",
        "name": "X-API-Key",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "API Key": []
    }
  ]
}

**Comment by Burgyn** [comment]
Hi.
Sorry for the late reply.
Please try new version `v2.0.2`
